### ISSUE TITLE
Dedicated host "manage_host_queue.log" fills rapidly

### ISSUE THREAD

**Issue by pnpritchard** [Shippable/support#1081]
I am using a dedicated host, and twice in the past week, the log file `/home/shippable/dpd/logs/manage_host_queue.log` has filled up my server disk (almost 200GB) very rapidly. In the file, it looks like the process gets trapped in some connection error, and this gets logged multiple times every millisecond:

```
2015-02-23 11:22:17,825 - manage_host_queue - WARNING - Unhandled exception! Pika disconnected
Traceback (most recent call last):
  File "/home/shippable/dpd/exchange.py", line 262, in run
    self._connection.ioloop.start()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 101, in start
    self.poller.start()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 385, in start
    self.poll()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 440, in poll
    self._handler(fileno, event, write_only=write_only)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 279, in _handle_events
    self._handle_read()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 307, in _handle_read
    self._on_data_available(data)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1145, in _on_data_available
    self._process_frame(frame_value)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1187, in _process_frame
    if self._process_callbacks(frame_value):
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1160, in _process_callbacks
    frame_value)                 # Args
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 61, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 232, in process
    callback(*args, **keywords)
TypeError: on_channel_closed() takes exactly 4 arguments (2 given)
```

Everything seems to return to normal after deleting the file and restarting the dedicated host (from shippable UI).

**Comment by manishas** [comment]
We have fixed this in an update that was deployed today. I'll give it a couple of days and check back in with you to see if you're still running into this. Thanks!

**Comment by pnpritchard** [comment]
Ok thanks! I will restart the dedicated hosts and let you know if it happens again.

**Comment by manishas** [comment]
Closing. Please re-open if you still have problems with this.
