### ISSUE TITLE
Build failed with “Cannot destroy container”

### ISSUE THREAD

**Issue by lkiesow** [Shippable/support#1104]
opencast-community / Matterhorn / Build: 167 failed with some internal error. This might be a problem on shippable:

 Container
 
```
 error occurred while removing container bb_opencast-community_matterhorn_167_2_545785e1a85d45d063d8db2d: 500 Server Error: Internal Server Error ("Cannot destroy container bb_opencast-community_matterhorn_167_2_545785e1a85d45d063d8db2d: Driver aufs failed to remove root filesystem 1b3bb1094a66cff2c427ba1641d07212dbe2c4b17cabc2d2c4e715048df66d0c: rename /data/aufs/diff/1b3bb1094a66cff2c427ba1641d07212dbe2c4b17cabc2d2c4e715048df66d0c /data/aufs/diff/1b3bb1094a66cff2c427ba1641d07212dbe2c4b17cabc2d2c4e715048df66d0c-removing: device or resource busy"): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception:  
 error occurred while removing container bb_opencast-community_matterhorn_167_2_545785e1a85d45d063d8db2d: 500 Server Error: Internal Server Error ("Cannot destroy container bb_opencast-community_matterhorn_167_2_545785e1a85d45d063d8db2d: Driver aufs failed to remove root filesystem 1b3bb1094a66cff2c427ba1641d07212dbe2c4b17cabc2d2c4e715048df66d0c: rename /data/aufs/diff/1b3bb1094a66cff2c427ba1641d07212dbe2c4b17cabc2d2c4e715048df66d0c /data/aufs/diff/1b3bb1094a66cff2c427ba1641d07212dbe2c4b17cabc2d2c4e715048df66d0c-removing: device or resource busy")
```

**Comment by manishas** [comment]
@lkiesow Here is the response from our engineering... suggestion is to restart the host - 

This is a very old bug in Docker. I've seen this happening locally while manually invoking docker rm. Restarting Docker did not seem to help when I ran in to this. I had to restart the box to be able to remove the container.

It looks like people are still running in to it with Docker 1.5. See docker/docker#3823 and docker/docker#9665.

**Comment by manishas** [comment]
@lkiesow Please let me know if the suggestion above helps.

I am closing this issue. Please re-open if it doesn't work for you.

**Comment by lkiesow** [comment]
The host is your server so I can't do much about this. I've seen other builds run through since then. I just wanted to let you know.

**Comment by manishas** [comment]
sorry, we thought you were using dedicated hosts. please let me know if this happens again..

**Comment by c0bra** [comment]
I just happened across this error (reformatted for readability):

```
Error response from daemon: Cannot destroy container <container-id>:
  Driver aufs failed to remove root filesystem <uuid>:
    rename /data/aufs/mnt/<uuid>/data/aufs/mnt/<uuid>-removing: device or resource busy
Error: failed to remove containers: [<container-id>]
```
