### ISSUE TITLE
New Docker build fails with erroneous --pull param set

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1138]
I am testing out your new Docker build support with a vanilla container, the build fails with the following output;

```
sudo docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag="peopleperhour/mmdata:master.74" .;
 |1425910189

flag provided but not defined: --pull



Usage: docker build [OPTIONS] PATH | URL | -



Build a new image from the source code at PATH



  --force-rm=false     Always remove intermediate containers, even after unsuccessful builds

  --no-cache=false     Do not use cache when building the image

  -q, --quiet=false    Suppress the verbose output generated by the containers

  --rm=true            Remove intermediate containers after a successful build

  -t, --tag=""         Repository name (and optionally a tag) to be applied to the resulting image in case of success

Repository File Count : 67
Repository Size : 1064529
-t, --tag="" Repository name (and optionally a tag) to be applied to the resulting image in case of success : Traceback (most recent call last): File "/home/shippable/ibl/step_listener.py", line 75, in handle_message_callback self.execute_step(build_plan, current_step, False) File "/home/shippable/ibl/step_listener.py", line 134, in execute_step raise e Exception: -t, --tag="" Repository name (and optionally a tag) to be applied to the resulting image in case of success
```

**Comment by pmoust** [comment]
Ref build: 54fdaa3da75bad0b009946d1

**Comment by ragsden** [comment]
@pmoust, We have upgraded docker to 1.5 for better stability and new features. Can you please reinitialize and redeploy your host and this issue should go away.
Sorry about the issue.

**Comment by pmoust** [comment]
DId so, however another issue comes up
![screenshot 2015-03-09 17 32 16](https://cloud.githubusercontent.com/assets/2493339/6558066/617b2e20-c682-11e4-9e5c-0a0054a9efc7.png)

Will start with fresh nodes to see how it copes. (said image is mentioned in `commit_container:` part of shippable.yaml, *and* declared in the new build settings).

**Comment by manishas** [comment]
@pmoust can you send us your Dockerfile to manisha@shippable.com? Thanks!

**Comment by manishas** [comment]
I am assuming this is fixed. Please re-open if this issue is still happening.
