### ISSUE TITLE
internal server error when attempting to enable project

### ISSUE THREAD

**Issue by henrjk** [Shippable/support#1183]
I am on page [https://app.shippable.com/projects/5508860d5ab6cc1352a33dde](https://app.shippable.com/projects/5508860d5ab6cc1352a33dde) and tried to enable the project for shippable. The related github project is https://github.com/henrjk/sample_ubuntu1204_python.

The reason I am doing this is that in my main project there is now a python part and I am trying to see in a python build logs what is needed. 

So I am logged in with my github credentials then I select the project and attempt to enable it. I then see a notification message showing an Internal Server Error with no further details. Then the page says:

This project is no longer available on Shippable. 
Go to dashboard

In Chrome's console I get these messages:
2015-03-17 20:59:52.603
angular.js:9778 Error: [$compile:ctreq] Controller 'accordion', required by directive 'accordionGroup', can't be found!
http://errors.angularjs.org/1.2.16/$compile/ctreq?p0=accordion&p1=accordionGroup
    at https://app.shippable.com/lib/angular/angular.js:78:12
    at getControllers (https://app.shippable.com/lib/angular/angular.js:6409:19)
    at nodeLinkFn (https://app.shippable.com/lib/angular/angular.js:6580:35)
    at delayedNodeLinkFn (https://app.shippable.com/lib/angular/angular.js:6798:11)
    at compositeLinkFn (https://app.shippable.com/lib/angular/angular.js:5982:15)
    at Scope.publicLinkFn [as $transcludeFn] (https://app.shippable.com/lib/angular/angular.js:5891:30)
    at link (https://app.shippable.com/lib/angular-bootstrap/ui-bootstrap-tpls-0.12.1.min.js:9:8548)
    at nodeLinkFn (https://app.shippable.com/lib/angular/angular.js:6579:13)
    at compositeLinkFn (https://app.shippable.com/lib/angular/angular.js:5982:15)
    at publicLinkFn (https://app.shippable.com/lib/angular/angular.js:5891:30) <div class="panel panel-default ng-isolate-scope" is-open="true">
2015-03-17 21:00:37.248api.shippable.com/workflow/enableRepoBuild:1 POST https://api.shippable.com/workflow/enableRepoBuild 500 (Internal Server Error)

The angular message happens when I select the project and before attempting to enable it, so this could be benign.

**Comment by henrjk** [comment]
Just for the fun of it I tried logging in with my bitbucket credentials and with that I can enable the github repo.  So I don't need a fix for now, but I am happy to try out stuff or provide more data if that helps.

**Comment by manishas** [comment]
Closing this issue. We couldn't repro this at our end, but if anything like this happens again, please re-open. Thanks!
