### ISSUE TITLE
Exception: HTTP code: 502

### ISSUE THREAD

**Issue by djindjic** [Shippable/support#1209]
is shippabe in operational status?
 I'm getting this error:

HTTP code: 502: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception: HTTP code: 502

**Comment by djindjic** [comment]
sorry, I have just see you tweet 3h ago
