### ISSUE TITLE
i/o Timeouts on index.docker.io

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1210]
Get https://index.docker.io/v1/repositories/shippableimages/ubuntu1404_nodejs/images: read tcp 162.242.195.84:443: i/o timeout: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception: Get https://index.docker.io/v1/repositories/shippableimages/ubuntu1404_nodejs/images: read tcp 162.242.195.84:443: i/o timeout

**Comment by chriskinsman** [comment]
Looks like it resolved itself
