### ISSUE TITLE
Exception: Connection to 54.172.43.70:5671 failed: _ssl.c:495: The handshake operation timed out

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#1225]
I have next error:

docker pull
Docker login
Docker pull vauxoo/odoo-80-image-shippable-auto:latest
Pulling image (latest) from vauxoo/odoo-80-image-shippable-auto, 
Pulling image (latest) from vauxoo/odoo-80-image-shippable-auto, endpoint: https://registry-1.docker.io/v1/, 
Pulling dependent layers, 
Download complete, 
Download complete, 
Download complete, 
Download complete, 
Download complete, 
Download complete, 
```python
Connection to 54.172.43.70:5671 failed: _ssl.c:495: The handshake operation timed out: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 177, in execute_step
    retry_count=0
  File "/home/shippable/dpd/base.py", line 43, in publish_message
    retry_count=retry_count + 1)
  File "/home/shippable/dpd/base.py", line 43, in publish_message
    retry_count=retry_count + 1)
  File "/home/shippable/dpd/base.py", line 43, in publish_message
    retry_count=retry_count + 1)
  File "/home/shippable/dpd/base.py", line 43, in publish_message
    retry_count=retry_count + 1)
  File "/home/shippable/dpd/base.py", line 43, in publish_message
    retry_count=retry_count + 1)
  File "/home/shippable/dpd/base.py", line 43, in publish_message
    retry_count=retry_count + 1)
  File "/home/shippable/dpd/base.py", line 32, in publish_message
    raise Exception(str(e))
Exception: Connection to 54.172.43.70:5671 failed: _ssl.c:495: The handshake operation timed out
```

**Comment by manishas** [comment]
can you post a link to the build? Thanks!

**Comment by moylop260** [comment]
now is working!
