### ISSUE TITLE
[issue] after_success coveralls - OpenSSL.SSL.SysCallError: (104, 'ECONNRESET'

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#1280]
I have a yaml file with next info
```yaml
...
after_success:
  coveralls
...
```

I saw in my shippable build next error
```python
coveralls
Submitting coverage to coveralls.io...
Traceback (most recent call last):
  File "/root/ve/bin/coveralls", line 9, in <module>
    load_entry_point('coveralls==0.5', 'console_scripts', 'coveralls')()
  File "/root/ve/local/lib/python2.7/site-packages/coveralls/cli.py", line 60, in main
    result = coverallz.wear()
  File "/root/ve/local/lib/python2.7/site-packages/coveralls/api.py", line 82, in wear
    response = requests.post(self.api_endpoint, files={'json_file': json_string})
  File "/root/ve/local/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/ve/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/root/ve/local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/ve/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/root/ve/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/root/ve/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/root/ve/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/root/ve/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 225, in sendall
    sent = self._send_until_done(data)
  File "/root/ve/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 215, in _send_until_done
    return self.connection.send(data)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 950, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
```

I'm using a custom image and my build example is:
(shippable build) [https://app.shippable.com/builds/55230538d378750b00dca76c]

**Comment by lekhab** [comment]
@moylop260 - trying to clean up some old issues that we never got around to. Is this still a valid issue?

**Comment by moylop260** [comment]
I have the same problem but we will desactivate coveralls in shippable.
Thank you
