### ISSUE TITLE
enable code coverage for golang

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1587]
I have a build configured for go. My configuration is pretty much the same as the sample in your docs. After completing a build successfully, however, there is no code coverage. I added some logging statements to my shippable.yml and at the after-script hook there is a file named ./shippable/codecoverage/coverage.xml. 

The code coverage info of my build does not reflect the results from this file.

What else do I need to configure in order to get this working?

**Comment by manishas** [comment]
@rvdwijngaard can you point me to a build link and also share your shippable.yml? Thanks!

**Comment by rvdwijngaard** [comment]
@manishas build https://app.shippable.com/builds/559149d0d3efa70c00ac48b9 for example; 

my shippable.yml file looks like this: 
```
language: go

go:
  - 1.4

env:
  global:
    - CI_REPORT=shippable/testresults/junit.xml
    - AWS_REGION=eu-west-1

before_install:
  - export GOPATH=$SHIPPABLE_GOPATH
  - source $HOME/.gvm/scripts/gvm
  - gvm install go$SHIPPABLE_GO_VERSION
  - gvm use go$SHIPPABLE_GO_VERSION
  - go get github.com/t-yuki/gocover-cobertura    
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/objx
  - go get github.com/stretchr/testify/assert
    
    # install local DynamoDB
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &  

# Make folders for the reports
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - go test -coverprofile=coverage.txt -covermode count ./
  - $GOPATH/bin/gocover-cobertura < coverage.txt > shippable/codecoverage/coverage.xml
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

after_script:
  - cp main ./shippable/buildoutput
  - cp -r api ./shippable/buildoutput/api
  - ls ./shippable -ltrR
  - cat ./shippable/codecoverage/coverage.xml
```

I think this problem is caused because of the GOPATH value. I made a fork of cobertura which was logging exceptions. Whan I run a build with that package it shows me the following exception: 
```
 $GOPATH/bin/gocover-cobertura < coverage.txt > shippable/codecoverage/coverage.xml
panic: can't find "encrypt.go": cannot find package "_/home/shippable/workspace/src/bitbucket.org/to-increase/my-repo/" in any of:
/home/shippable/.gvm/gos/go1.4/src/_/home/shippable/workspace/src/bitbucket.org/to-increase/my-repo (from $GOROOT)
/home/shippable/.gvm/pkgsets/go1.4/global/src/_/home/shippable/workspace/src/bitbucket.org/to-increase/my-repo (from $GOPATH)
goroutine 1 [running]:
main.(*Coverage).parseProfiles(0xc208011810, 0xc208032380, 0x8, 0x8, 0x0, 0x0)
/home/shippable/.gvm/pkgsets/go1.4/global/src/github.com/rvdwijngaard/gocover-cobertura/gocover-cobertura.go:55 +0x136
main.convert(0x7fdd682b09f8, 0xc208034000, 0x7fdd682b0998, 0xc208034008)
/home/shippable/.gvm/pkgsets/go1.4/global/src/github.com/rvdwijngaard/gocover-cobertura/gocover-cobertura.go:35 +0x3cd
main.main()
/home/shippable/.gvm/pkgsets/go1.4/global/src/github.com/rvdwijngaard/gocover-cobertura/gocover-cobertura.go:19 +0x79
```

**Comment by jdextraze** [comment]
I also have an issue with code coverage. The xml file is generated, but the coverage tab is always showing 0% for each packages. Example build: https://app.shippable.com/builds/563c022da92e8b0c00ea60e2

**Comment by manishas** [comment]
We have redone our test and coverage reports handling and this is now fixed. closing.
