### ISSUE TITLE
API Rate limit 

### ISSUE THREAD

**Issue by Nalum** [Shippable/support#1694]
I am trying to log into shippable and I am getting the following error:

```
failed to fetch user profile (status: 403 data: {"message":"API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"})
   at /home/shippable/www/node_modules/passport-github/lib/passport-github/strategy.js:90:28
   at passBackControl (/home/shippable/www/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:142:7)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)
```

**Comment by Nalum** [comment]
Actually this looks like it's a limit of Github, though why I'm hitting it I don't know.
