### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#1715]
After experiencing some loading issues on app.shippable.com today, I cleared all my cookies and went to log in again via Bitbucket only to receive an error like this:

```
failed to obtain access token (status: 400 data: Invalid request token.)
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:134:36
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:465:22
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)
```

The URL of that page looks like `https://app.shippable.com/auth/bitbucket/identify?oauth_verifier=<number>&oauth_token=<text>`

**Comment by rockerhieu** [comment]
I got this problem too.

**Comment by rageshkrishna** [comment]
Things should be back to normal now. Please let me know if you're still having issues accessing the service.

**Comment by mbrodala** [comment]
I still get the error upon simply reloading the page, but starting anew from app.shippbable.com works.
