### ISSUE TITLE
Bitbucket integration down

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#1726]
Here is the error on login:

failed to obtain access token (status: 400 data: Invalid request token.)
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:134:36
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:465:22
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)

**Comment by JADurham909** [comment]
Actually this turned out to be related to something in the browser.  When I switched from Safari to Chrome is started working.  I will leave this open just so you are aware of it.

**Comment by lekhab** [comment]
@JADurham909: Apologies - this occurred when we were having some intermittent issues today morning, which have since been resolved. I am not able to reproduce this anymore. Please refresh the cache and try again. will re-open if this continues to be an issue.
