### ISSUE TITLE
Issue uploading artifacts

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1791]
Hi,

I am getting issue uploading artifacts to S3. The log says following

~~~
Traceback (most recent call last):
File "/root/ve/bin/aws", line 27, in <module>
sys.exit(main())
File "/root/ve/bin/aws", line 23, in main
return awscli.clidriver.main()
File "/root/ve/local/lib/python2.7/site-packages/awscli/clidriver.py", line 47, in main
driver = create_clidriver()
File "/root/ve/local/lib/python2.7/site-packages/awscli/clidriver.py", line 56, in create_clidriver
event_hooks=emitter)
File "/root/ve/local/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
modules = _import_plugins(plugin_mapping)
File "/root/ve/local/lib/python2.7/site-packages/awscli/plugin.py", line 61, in _import_plugins
module = __import__(path, fromlist=[module])
File "/root/ve/local/lib/python2.7/site-packages/awscli/handlers.py", line 48, in <module>
from awscli.customizations.s3endpoint import register_s3_endpoint
File "/root/ve/local/lib/python2.7/site-packages/awscli/customizations/s3endpoint.py", line 29, in <module>
from botocore.handlers import fix_s3_host
ImportError: cannot import name fix_s3_host
~~~

**Comment by lekhab** [comment]
@naveensky - can you paste some build links, pls?

**Comment by naveensky** [comment]
yup, here we go https://app.shippable.com/builds/55cd1d88badd4e0b0007773a

I have for now disabled artifacts upload on this project, but this build had that enabled

**Comment by lekhab** [comment]
@naveensky: I see you are using secure variables. We had a bug last week, which resulted in SSH keys being reset. So the encrypted vars need to be reset as well. Can you please re-encrypt and see if that works?

**Comment by lekhab** [comment]
closing this. Please let me know if this is still an issue.
