### ISSUE TITLE
Get an error when running 'pip --version' during setup_ve

### ISSUE THREAD

**Issue by pcflmb** [Shippable/support#1909]
Output from running the command:
```bash
Traceback (most recent call last):
  File "/home/shippable/build_ve/python/2.7/bin/pip", line 7, in 
    from pip import main
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/__init__.py", line 11, in 
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in 
    from pip.download import path_to_url
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/download.py", line 22, in 
    from pip._vendor import requests, six
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in 
    from . import utils
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 25, in 
    from .compat import parse_http_list as _parse_list_header
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in 
    from .packages import chardet
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in 
    from . import urllib3
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 16, in 
    from .connectionpool import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 33, in 
    from .connection import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 41, in 
    from .util import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in 
    from .ssl_ import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 4, in 
    from ..exceptions import SSLError, InsecurePlatformWarning
ImportError: cannot import name InsecurePlatformWarning
```

Apparently a solution is to update python 2.7 to at least 2.7.9... currently Shippable is building with 2.7.3.  Why is Shippable not on the newest patch release of 2.7?

**Comment by pcflmb** [comment]
Guys this is still happening!! What's even more odd is that Shippable reports all tests passing even though none of them were run!

**Comment by avinci** [comment]
Let me look into this...I think we don't force, minor version. I think the base image needs to be updated. We will have the latest base image up in the next week.

**Comment by catskul** [comment]
Happing to us as well


```
Traceback (most recent call last):
  File "/home/shippable/build_ve/python/2.7/bin/pip", line 7, in 
    from pip import main
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/__init__.py", line 11, in 
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in 
    from pip.download import path_to_url
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/download.py", line 22, in 
    from pip._vendor import requests, six
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in 
    from . import utils
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 25, in 
    from .compat import parse_http_list as _parse_list_header
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in 
    from .packages import chardet
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in 
    from . import urllib3
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 16, in 
    from .connectionpool import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 33, in 
    from .connection import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 41, in 
    from .util import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in 
    from .ssl_ import (
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 4, in 
    from ..exceptions import SSLError, InsecurePlatformWarning
ImportError: cannot import name InsecurePlatformWarning
```

**Comment by catskul** [comment]
but intermittently. Seems like some minions are affected and others are not.

**Comment by manishas** [comment]
Our build system was upgraded recently and you should not see this any more. Closing.
