### ISSUE TITLE
authorized organization not registered in shippable

### ISSUE THREAD

**Issue by jim-bo** [Shippable/support#1913]
I had the shippable permission request approved (and received notification from github). Then when I log into shippable I get the following error:

failed to fetch user profile (status: 401 data: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3"})
   at /home/shippable/www/node_modules/passport-github/lib/passport-github/strategy.js:90:28
   at passBackControl (/home/shippable/www/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)

**Comment by avinci** [comment]
@jim-bo If the org is a private org, you need to go to account settings and make sure private repos are turned on. Can you check to see if you have this turned on?

Docs are here
http://docs.shippable.com/account_settings/#github-identity

I take the underlying point here that we need to make this better. I am adding that to the requirement.

**Comment by manishas** [comment]
@jim-bo i am closing this issue since i am assuming the suggestion above worked. Please let us know if you have any questions.
