### ISSUE TITLE
Chrome selenium Protractor e2e tests driver version issue

### ISSUE THREAD

**Issue by lukemadera** [Shippable/support#2013]
I've been through the following threads and have things working with Firefox (though tests do not seem to pass - sporadic results, as has been my experience with Firefox, even locally, so we need to use Chrome, which is the only one that reliably passes for me).

https://github.com/Shippable/support/issues/609
https://github.com/Shippable/support/issues/258
https://github.com/Shippable/support/issues/253
https://github.com/Shippable/support/issues/285
https://github.com/Shippable/support/issues/732
https://github.com/Shippable/support/issues/818

Log output:
```
>> 17:36:14.532 INFO - Launching a standalone Selenium Server
>> Setting system property webdriver.chrome.driver to node_modules/protractor/selenium/chromedriver
>> 17:36:14.594 INFO - Java: Oracle Corporation 24.72-b04
>> 17:36:14.594 INFO - OS: Linux 3.13.0-57-generic amd64
>> 17:36:14.613 INFO - v2.47.1, with Core v2.47.1. Built from revision 411b314
>> 17:36:14.737 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
>> registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
>> 17:36:14.738 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
>> registration capabilities Capabilities [{platform=WINDOWS, browserName=MicrosoftEdge, version=}] does not match the current platform LINUX
>> 17:36:14.738 INFO - Driver class not found: com.opera.core.systems.OperaDriver
>> 17:36:14.738 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
>> 17:36:14.854 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
>> 17:36:14.854 INFO - Selenium Server is up and running
server.js opening new database connection
[success] connected to db at localhost:27017/test_temp
>> Done waiting after 1501ms

Running "shell:protractor" (shell) task
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
>> 17:36:16.764 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
>> 17:36:16.792 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
>> Starting ChromeDriver 2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1) on port 12845
>> Only local connections are allowed.
Realtime inited
Cronjoblocal inited
Express server listening at http://localhost:3005/ in development mode
>> 17:36:19.642 WARN - Exception thrown
>> java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
>> Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
>> System info: host: '1ac8301f1a2e', ip: '172.17.3.36', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-57-generic', java.version: '1.7.0_72'
>> Driver info: driver.version: unknown
>> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>> 	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
>> 	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
>> 	at org.openqa.selenium.remote.server.DefaultSession.(DefaultSession.java:119)
>> 	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
>> 	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:125)
>> 	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:58)
>> 	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
>> 	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
>> 	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:175)
>> 	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:202)
>> 	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:164)
>> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
>> 	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:130)
>> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
>> 	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
>> 	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
>> 	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
>> 	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
>> 	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
>> 	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
>> 	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
>> 	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
>> 	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
>> 	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
>> 	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
>> 	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
>> Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
>> Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
>> System info: host: '1ac8301f1a2e', ip: '172.17.3.36', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-57-generic', java.version: '1.7.0_72'
>> Driver info: driver.version: unknown
>> 	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
>> 	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
>> 	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
>> 	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
>> 	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
>> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>> 	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
>> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>> 	at java.lang.Thread.run(Thread.java:745)
>> Caused by: java.lang.reflect.InvocationTargetException
>> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
>> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>> 	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
>> 	... 9 more
>> Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome version must be >= 43.0.2357.0
>>   (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-57-generic x86_64) (WARNING: The server did not provide any stacktrace information)
>> Command duration or timeout: 1.74 seconds
>> Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
>> System info: host: '1ac8301f1a2e', ip: '172.17.3.36', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-57-generic', java.version: '1.7.0_72'
>> Driver info: org.openqa.selenium.chrome.ChromeDriver
>> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
>> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>> 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
>> 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
>> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
>> 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
>> 	at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:128)
>> 	at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:141)
>> 	at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:170)
>> 	at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:138)
>> 	... 14 more
>> 17:36:19.663 WARN - Exception: unknown error: Chrome version must be >= 43.0.2357.0
>>   (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-57-generic x86_64) (WARNING: The server did not provide any stacktrace information)
>> Command duration or timeout: 1.74 seconds
>> Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
>> System info: host: '1ac8301f1a2e', ip: '172.17.3.36', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-57-generic', java.version: '1.7.0_72'
>> Driver info: org.openqa.selenium.chrome.ChromeDriver

/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: unknown error: Chrome version must be >= 43.0.2357.0
  (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-57-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.74 seconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: '1ac8301f1a2e', ip: '172.17.3.36', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-57-generic', java.version: '1.7.0_72'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at new bot.Error (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at [object Object].promise.ControlFlow.runInFrame_ (eval at  (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), :1857:20)
    at [object Object].goog.defineClass.notify (eval at  (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), :2448:25)
    at [object Object].promise.Promise.notify_ (eval at  (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), :564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (eval at  (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), :553:15)
    at [object Object].goog.async.run.processWorkQueue [as onTimeout] (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/lib/runner.js:180:37)
    at driverprovider_.setupEnv.then.then.then.frameworkPath (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/lib/runner.js:256:21)
    at _fulfilled (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/shippable/workspace/src/github.com/DropPrice/dropprice1/node_modules/protractor/node_modules/q/q.js:525:49
[launcher] Process exited with error code 1
Warning: Done, with errors. Use --force to continue.

Aborted due to warnings.
```

And shippable config:
```
# language setting
language: node_js

node_js: "0.10.40"

# for selenium e2e
#addons:
#  firefox: "28.0"

services:
  - mongodb
  - selenium

cache: true

env:
  matrix:
    - PARALLEL_BUILD=deploy
    #- PARALLEL_BUILD=teste2e
    - PARALLEL_BUILD=testBackend
    - PARALLEL_BUILD=testFrontend

before_install:
  - npm cache clean
  # for selenium chrome driver
  - if [ "$PARALLEL_BUILD" == "teste2e" ]; then curl -o /tmp/chromedriver.zip -L http://chromedriver.storage.googleapis.com/2.19/chromedriver_linux64.zip &&
    unzip /tmp/chromedriver.zip -d /home/shippable/bin &&
    chmod +x /home/shippable/bin/chromedriver &&
    echo '#!/bin/bash' | sudo tee /usr/bin/google-chrome &&
    echo 'exec /usr/bin/chrome --no-sandbox --disable-gpu \"$@\"' | sudo tee -a /usr/bin/google-chrome &&
    sudo chmod +x /usr/bin/google-chrome; fi

before_script:
  - chmod +x ./docker-dropprice-deploy.sh
  - bower install
  # for selenium e2e
  - if [ "$PARALLEL_BUILD" == "teste2e" ]; then export DISPLAY=:99.0 &&
    /etc/init.d/xvfb start; fi
  # set environment - needed for e2e tests selenium path but breaks things otherwise (want to keep other tests local)
  #- echo "{\"environment\":\"dropprice_scaling\"}" > config_environment.json
  - echo "{\"environment\":\"mac\"}" > config_environment.json
  - if [ "$PARALLEL_BUILD" == "teste2e" ]; then ./node_modules/protractor/bin/webdriver-manager update; fi
  - grunt q

script:
  - if [ "$PARALLEL_BUILD" == "testFrontend" ]; then grunt karma-cov; fi
  - if [ "$PARALLEL_BUILD" == "testBackend" ]; then grunt node-test-server && grunt jasmine_node; fi
  - if [ "$PARALLEL_BUILD" == "teste2e" ]; then grunt e2e; fi
  - if [ "$BRANCH" == "master" -a "$PARALLEL_BUILD" == "deploy" ]; then cat docker-dropprice-deploy.sh | ssh root@162.243.153.52; fi
  - if [ "$BRANCH" == "dev2" -a "$PARALLEL_BUILD" == "deploy" ]; then cat ci-dropprice-deploy.sh | ssh lmadera@107.170.216.136; fi
  - if [ "$BRANCH" == "prod" -a "$PARALLEL_BUILD" == "deploy" ]; then cat ci-dropprice-deploy-prod.sh | ssh lmadera@dropprice.com; fi

after_script:
  # for selenium e2e
  - if [ "$PARALLEL_BUILD" == "teste2e" ]; then /etc/init.d/xvfb stop; fi

# after_success:

```

How can I get (Protractor) Selenium end to end tests running with Chrome?

Thanks!

**Comment by ric03uec** [comment]
@lukemadera this might be because of incompatible `selenium` and `chromedriver` versions on shippable. 
we're using selenium: 2.35.0. can you tell me which version of selenium are you using to test locally?

**Comment by lukemadera** [comment]
@ric03uec Ahh. As mentioned we use Angular Protractor, which installs both Selenium and Chromedriver (which are versions 2.19 for chrome and 2.47.1 for selenium). That's how I run locally and how I tried originally doing on shippable but that didn't seem to work so via the threads I tried installing selenium and chromedriver the "shippable way"?

Any reason shippable's selenium is so far behind? And Is there a way I can specify the selenium version to use 2.47.1? Or I suppose specify and older ChromeDriver? Is there a list of which versions match with each other (i.e. what chromedriver version would I used with selenium 2.35)?

**Comment by lukemadera** [comment]
No luck - I tried with selenium 2.45 and Chromedriver 2.15 and same error. Seems it's not finding / able to run chrome. Is there a "chrome" addon similar to Firefox that could be used? Since the tests are at least running with the Firefox addon.

**Comment by manishas** [comment]
we have upgraded selenium version on our [new official images](https://hub.docker.com/u/drydock/) and the build system has also been upgraded since this issue was reported.

Please try with the new images and let us know if this is still happening.
