### ISSUE TITLE
Failed to fetch user profile

### ISSUE THREAD

**Issue by xun91** [Shippable/support#2127]
Receive an error saying. Then I tried to delete the integration from shippable and add the new integration again. but I'm still getting this error.

```
failed to fetch user profile
   at /home/shippable/www/node_modules/passport-bitbucket/lib/passport-bitbucket/strategy.js:74:28
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)
```

**Comment by manishas** [comment]
please follow the issue https://github.com/Shippable/support/issues/2126 for updates. we're actively looking into this since something seems to have changed on the bitbucket end and some calls to their API is failing unexpectedly.
