### ISSUE TITLE
Bitbucket integration error, unable to login or push

### ISSUE THREAD

**Issue by archeons** [Shippable/support#2128]
Hi, I am experiencing this error below:

failed to fetch user profile
   at /home/shippable/www/node_modules/passport-bitbucket/lib/passport-bitbucket/strategy.js:74:28
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13) 

Is Shippable down?

**Comment by manishas** [comment]
We're actively looking into this since something seems to have changed on the bitbucket end and some calls to their API is failing unexpectedly. Shippable is not down but our integration with bitbucket is experiencing issues at the moment.

please follow the issue #2126 for updates.
