### ISSUE TITLE
Cannot login with bitbucket

### ISSUE THREAD

**Issue by catskul** [Shippable/support#2145]
Fails with the following message:

```
failed to obtain request token (status: 403 data: This endpoint does not support token-based authentication)
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:196:36
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:543:17
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)
```

**Comment by trriplejay** [comment]
I suspect something's going on with bitbucket, but we're investigating.

**Comment by trriplejay** [comment]
I think this has resolved itself now.  Feel free to re-open if it's still happening to you.

**Comment by catskul** [comment]
Works. Thanks for the update.
