### ISSUE TITLE
ImportError: cannot import name PolymorphicModel

### ISSUE THREAD

**Issue by jbowman1107** [Shippable/support#2223]
With no changes to our branches, we are now getting the following error in the Script. None of our branches can currently build due to this.

/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/dotenv.py:53: UserWarning: Not reading .env - it doesn't exist.
  warnings.warn("Not reading {0} - it doesn't exist.".format(dotenv))
DEBUG 2016-01-23 11:55:16,970 base 20043 140549104699136 Configuring Raven for host: 
INFO 2016-01-23 11:55:16,970 base 20043 140549104699136 Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "manage.py", line 13, in 
    execute_from_command_line(sys.argv)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/filer/models/__init__.py", line 2, in 
    from filer.models.clipboardmodels import *
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/filer/models/clipboardmodels.py", line 7, in 
    from filer.models import filemodels
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/filer/models/filemodels.py", line 13, in 
    from polymorphic import PolymorphicModel, PolymorphicManager
ImportError: cannot import name PolymorphicModel
/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/dotenv.py:53: UserWarning: Not reading .env - it doesn't exist.
  warnings.warn("Not reading {0} - it doesn't exist.".format(dotenv))
DEBUG 2016-01-23 11:55:20,657 base 20055 140288771639040 Configuring Raven for host: 
INFO 2016-01-23 11:55:20,657 base 20055 140288771639040 Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "manage.py", line 13, in 
    execute_from_command_line(sys.argv)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/filer/models/__init__.py", line 2, in 
    from filer.models.clipboardmodels import *
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/filer/models/clipboardmodels.py", line 7, in 
    from filer.models import filemodels
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/filer/models/filemodels.py", line 13, in 
    from polymorphic import PolymorphicModel, PolymorphicManager
ImportError: cannot import name PolymorphicModel

**Comment by manishas** [comment]
This issue was opened before the upgraded build system was released last week.

Please let us know if you still run into this and we will reopen and investigate further. Thanks!
