### ISSUE TITLE
HTTPS/SNI error for api.shippable.com at "wait_for_exit"

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2293]
All of our current builds [fail on the `wait_for_exit` step](https://app.shippable.com/runs/56d56a5235921e0c0055afc5):

```
sudo docker logs -f c.exec.our-project.1135.1
PATH=/root/.phpenv/bin:/root/.phpenv/extensions:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/shippable/cexec/bin:/home/shippable/cexec/bin
Booting up CEXEC
Running CEXEC script
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
/home/shippable/cexec/dist/main/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
/home/shippable/cexec/dist/main/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
/home/shippable/cexec/dist/main/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
# ... repeated 94 times
Traceback (most recent call last):
  File "", line 8, in 
  File "execute.py", line 120, in run
    self._push_coverage_results()
  File "execute.py", line 160, in _push_coverage_results
    coverage_results = json.loads(coverage_results)
  File "json/__init__.py", line 338, in loads
  File "json/decoder.py", line 366, in decode
  File "json/decoder.py", line 384, in raw_decode
ValueError: No JSON object could be decoded
main returned -1
```

**Comment by pquentin** [comment]
We are affected too.

**Comment by rageshkrishna** [comment]
We've identified the issue. This will be fixed soon.

**Comment by mbrodala** [comment]
Looking forward to this since this is the last issue which lets our [builds fail](https://app.shippable.com/runs/56d6c527d6078c0c005f6c5c) AFAIS.

**Comment by rageshkrishna** [comment]
Very close to getting this fixed. Just waiting for the AMI snapshot to finish.

**Comment by rageshkrishna** [comment]
@mbrodala This should be in now. Please kick off a couple of builds and let me know how it goes.

**Comment by mbrodala** [comment]
@rageshkrishna That seems to have fixed the issue ([one](https://app.shippable.com/runs/56d6d0e987a3710b0047a561), [two](https://app.shippable.com/runs/56d6d19c87a3710b0047c549), [three](https://app.shippable.com/runs/56d6d2c06b86640c0048419e)). If it occurs again, I'll let you know. Thanks a lot!

And one more congratulations to the now blazingly fast builds. :-)
