### ISSUE TITLE
Build constantly failing (cannot install several gems) for Rails application

### ISSUE THREAD

**Issue by ondrejfuhrer** [Shippable/support#2367]
Hello,

I tried several things that I saw in different issues, but nothing seems to be working for me right now and the build is constantly failing.

My shippable.yml:
```
language: ruby

rvm:
  - 2.3.0

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libpq-dev
  - gem install bundler --pre

# ensure the test output and coverage dirs are created
before_script:
  - mkdir -p shippable/testresults
  - RAILS_ENV=test rake db:migrate

# write the rspec tests to the output dir
script:
  - rspec -o shippable/testresults/results.xml
``` 

Result from console:
```
bundle install --gemfile=$SHIPPABLE_GEMFILE $SHIPPABLE_BUNDLER_ARGS
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Installing rake 11.0.1
Installing i18n 0.7.0
Using json 1.8.3
Installing minitest 5.8.4
Installing thread_safe 0.3.5
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile2 2.0.0
Installing rack 1.6.4
Installing mime-types 2.99.1
Installing arel 6.0.3
Installing addressable 2.4.0
Installing execjs 2.6.0
Installing awesome_print 1.6.1
Installing bcrypt 3.1.11 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/bcrypt-3.1.11/ext/mri
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160311-2699-1ex913t.rb extconf.rb
creating Makefile

current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/bcrypt-3.1.11/ext/mri
make "DESTDIR=" clean

current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/bcrypt-3.1.11/ext/mri
make "DESTDIR="
compiling bcrypt_ext.c
compiling crypt_blowfish.c
compiling crypt.c
compiling crypt_gensalt.c
compiling wrapper.c
linking shared-object bcrypt_ext.so
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [bcrypt_ext.so] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/bcrypt-3.1.11 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/bcrypt-3.1.11/gem_make.out
Installing coderay 1.1.1
Installing debug_inspector 0.0.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/debug_inspector-0.0.2/ext/debug_inspector
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160311-2699-1ivmooq.rb extconf.rb
creating Makefile

current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/debug_inspector-0.0.2/ext/debug_inspector
make "DESTDIR=" clean

current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/debug_inspector-0.0.2/ext/debug_inspector
make "DESTDIR="
compiling debug_inspector.c
linking shared-object debug_inspector.so
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [debug_inspector.so] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/debug_inspector-0.0.2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/debug_inspector-0.0.2/gem_make.out
Installing sass 3.4.21
Installing bootstrap_form 2.3.0
Installing uniform_notifier 1.9.0
Installing byebug 8.2.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/ext/byebug
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160311-2699-1683f9k.rb extconf.rb
creating Makefile

current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/ext/byebug
make "DESTDIR=" clean

current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/ext/byebug
make "DESTDIR="
compiling context.c
compiling locker.c
compiling breakpoint.c
compiling threads.c
compiling byebug.c
linking shared-object byebug/byebug.so
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [byebug.so] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/byebug-8.2.2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/byebug-8.2.2/gem_make.out
Installing callsite 0.0.11
Installing cancancan 1.13.1
Installing coffee-script-source 1.10.0
Installing thor 0.19.1
Installing concurrent-ruby 1.0.1
Installing orm_adapter 0.5.0
Installing diff-lcs 1.2.5
Installing multipart-post 2.0.0
Installing ffaker 2.2.0
Installing ffi 1.9.10 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/ffi-1.9.10/ext/ffi_c
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160311-2699-xflrb0.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:657:in `try_ldflags'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:1813:in `pkg_config'
	from extconf.rb:15:in `'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/ffi-1.9.10 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/gem_make.out
Installing formatador 0.2.5
Installing git-version-bump 0.15.1
Installing multi_xml 0.5.5
Installing rb-fsevent 0.9.7
Installing lumberjack 1.0.10
Installing nenv 0.3.0
Installing shellany 0.0.1
Installing method_source 0.8.2
Installing slop 3.6.0
Installing guard-compat 1.2.1
Installing rspec-support 3.4.1
Installing tilt 2.0.2
Installing hashie 3.4.3
Installing multi_json 1.11.2
Installing jwt 1.5.1
Installing mini_magick 4.4.0
Installing nested_form 0.3.2
Installing pg 0.18.4 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/pg-0.18.4/ext
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160311-2699-gkmg00.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
checking for libpq-fe.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:1144:in `block in find_header'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:1143:in `find_header'
	from extconf.rb:47:in `'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/pg-0.18.4 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/gem_make.out
Using bundler 1.12.0.pre.2
Installing remotipart 1.2.1
Installing safe_yaml 1.0.4
Installing spring 1.6.4
Installing sqlite3 1.3.11 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/sqlite3-1.3.11/ext/sqlite3
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160311-2699-1kuacfl.rb extconf.rb
checking for sqlite3.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/lib
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:1144:in `block in find_header'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:1143:in `find_header'
	from extconf.rb:30:in `'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/sqlite3-1.3.11/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/sqlite3-1.3.11 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/sqlite3-1.3.11/gem_make.out
Installing state_machines 0.4.0
Installing rdoc 4.2.2
Installing tzinfo 1.2.2
Installing nokogiri 1.6.7.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160311-2699-1b1f7ar.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:522:in `with_werror'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:80:in `nokogiri_try_compile'
	from extconf.rb:87:in `block in add_cflags'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/mkmf.rb:629:in `with_cflags'
	from extconf.rb:86:in `add_cflags'
	from extconf.rb:336:in `'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.7.2/gem_make.out
Installing rack-test 0.6.3
Installing warden 1.2.6
Installing mail 2.6.3
Installing autoprefixer-rails 6.3.3.1
Installing uglifier 2.7.2
An error occurred while installing bcrypt (3.1.11), and Bundler cannot continue.
Make sure that `gem install bcrypt -v '3.1.11'` succeeds before bundling.
```

Can you please help me investigate, what is the problem?

Thank you.

**Comment by ondrejfuhrer** [comment]
Fixed by adding this line to `before_install` section:
```
- sudo apt-get -y install libgmp-dev
```
