### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by lanzalibre** [Shippable/support#2546]
pip install awsebcli 1s  
    Traceback (most recent call last):
      File "/usr/local/bin/pip", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
        locale.setlocale(locale.LC_ALL, '')
      File "/usr/lib/python2.7/locale.py", line 579, in setlocale
        return _setlocale(category, locale)
    locale.Error: unsupported locale setting

[Link to the build failure](https://app.shippable.com/runs/571631f64990480c00e5b8d5)
  
shippable.yml:

     language: python
     env:
       global:
         - SERVICE=web
         - PROJECT_ID=web # Project ID for existing GCP project
         - REGISTRY_ACCOUNT=myregistryid.dkr.ecr.us-east-1.amazonaws.com/myregistryname 
    build:
      pre_ci:
        - docker build -t $SERVICE:latest -f configs/docker/production/Dockerfile.web .
      pre_ci_boot:
        image_name: $REGISTRY_ACCOUNT
        image_tag: latest
        pull: false
        options: --privileged=true
      push:
        - docker tag -f $SERVICE:latest $REGISTRY_ACCOUNT:$PROJECT_ID.$BUILD_NUMBER
        - docker push $REGISTRY_ACCOUNT:$PROJECT_ID.$BUILD_NUMBER
    
    integrations:
      deploy:
        - integrationName: "AWS_xxxxxx"
          type: aws
          target: eb_docker
          application_name: "My First Elastic Beanstalk Application"
          env_name: "Default-Environment"
          bucket_name: "elasticbeanstalk-us-east-1-585295121647"
          region: "us-east-1"
          image_name: "myregistryid.dkr.ecr.us-east-1.amazonaws.com/myregistryname"
          image_tag: "$PROJECT_ID.$BUILD_NUMBER"
      hub:
          - integrationName: new_keys_ecr
            type: ecr
            agent_only: true

**Comment by lanzalibre** [comment]
Ok, it seems to be related with the build image. I fixed it with:
    pre_ci_boot:
      image_name: drydock/u14pytpls
      image_tag: tip
      pull: false
