### ISSUE TITLE
hanging at build step "Running job on customer's build node"

### ISSUE THREAD

**Issue by amondnet** [Shippable/support#2623]
### Description of your issue:

Today all build is not started and time out is occurred.

- Link to the build failure

https://app.shippable.com/runs/573ad8082b07180c00460ffd
https://app.shippable.com/runs/573ad6c35419f10f00c35d2a

` Running job on customer's build node for subscriptionId: 54cfd6515ab6cc13528a90bc`

![b](https://cloud.githubusercontent.com/assets/1964421/15328189/fc8d6708-1c8e-11e6-8f7b-25e8080462c3.PNG)

**Comment by amondnet** [comment]
```shell
$ docker ps

CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS               NAMES
511c07146a86        shipimg/mexec:master.144   "/home/shippable/mexe"   6 hours ago         Up 3 seconds                            shippable-mexec-5730cb632461c00c002904b0
```


```shell 
$ docker logs container

INFO:listen - listen:Executing docker restart -t=0 shippable-mexec-5730cb632461c00c002904b0
Booting up MEXEC..
INFO:listen - listen:Inside MEXEC listener
INFO:listen - listen:MEXEC boot successful
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
INFO:listen - listen:url amqps://hapodarexupabaqe:3raQQ4o72euaDQPQ@msg.shippable.com:5671/shippable?heartbeat_interval=0
INFO:listen - listen:Connecting to amqps://hapodarexupabaqe:3raQQ4o72euaDQPQ@msg.shippable.com:5671/shippable?heartbeat_interval=0
INFO:pika.adapters.base_connection:Connecting to 52.0.157.66:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 52.0.157.66:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 52.0.157.66:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 52.0.157.66:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 52.0.157.66:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 52.0.157.66:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 54.236.80.211:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 54.236.80.211:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 54.236.80.211:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out
WARNING:pika.connection:Could not connect, 0 attempts left
ERROR:listen - listen:Connection failed to open: Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out, retrying in 5 seconds
ERROR:listen - listen:Error starting MEXEC listener: 'NoneType' object has no attribute 'ioloop': Traceback (most recent call last):
  File "/home/shippable/mexec/listen.py", line 58, in main
    self.message_listener.run()
  File "/home/shippable/mexec/message_listener.py", line 165, in run
    self.connection = self.__connect()
  File "/home/shippable/mexec/message_listener.py", line 39, in __connect
    stop_ioloop_on_close=False)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 52, in __init__
    stop_ioloop_on_close)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 718, in connect
    self.callbacks.process(0, self.ON_CONNECTION_ERROR, self, self, error)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 61, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 232, in process
    callback(*args, **keywords)
  File "/home/shippable/mexec/message_listener.py", line 74, in __on_connection_open_error
    self.connection.ioloop.stop()
AttributeError: 'NoneType' object has no attribute 'ioloop'

INFO:listen - listen:Removing log handlers
INFO:listen - listen:Restarting mexec...
INFO:listen - listen:Executing docker restart -t=0 shippable-mexec-5730cb632461c00c002904b0
Booting up MEXEC..
INFO:listen - listen:Inside MEXEC listener
INFO:listen - listen:MEXEC boot successful
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
INFO:listen - listen:url amqps://hapodarexupabaqe:3raQQ4o72euaDQPQ@msg.shippable.com:5671/shippable?heartbeat_interval=0
INFO:listen - listen:Connecting to amqps://hapodarexupabaqe:3raQQ4o72euaDQPQ@msg.shippable.com:5671/shippable?heartbeat_interval=0
INFO:pika.adapters.base_connection:Connecting to 52.0.157.66:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 52.0.157.66:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 52.0.157.66:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 52.0.157.66:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 52.0.157.66:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 52.0.157.66:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 54.236.80.211:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 54.236.80.211:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out
INFO:pika.adapters.base_connection:Connecting to 54.236.80.211:5671 with SSL
WARNING:pika.adapters.base_connection:Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out
WARNING:pika.connection:Could not connect, 0 attempts left
ERROR:listen - listen:Connection failed to open: Connection to 54.236.80.211:5671 failed: _ssl.c:495: The handshake operation timed out, retrying in 5 seconds
ERROR:listen - listen:Error starting MEXEC listener: 'NoneType' object has no attribute 'ioloop': Traceback (most recent call last):
  File "/home/shippable/mexec/listen.py", line 58, in main
    self.message_listener.run()
  File "/home/shippable/mexec/message_listener.py", line 165, in run
    self.connection = self.__connect()
  File "/home/shippable/mexec/message_listener.py", line 39, in __connect
    stop_ioloop_on_close=False)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 52, in __init__
    stop_ioloop_on_close)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 718, in connect
    self.callbacks.process(0, self.ON_CONNECTION_ERROR, self, self, error)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 61, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pika/callback.py", line 232, in process
    callback(*args, **keywords)
  File "/home/shippable/mexec/message_listener.py", line 74, in __on_connection_open_error
    self.connection.ioloop.stop()
AttributeError: 'NoneType' object has no attribute 'ioloop'

INFO:listen - listen:Removing log handlers
INFO:listen - listen:Restarting mexec...
INFO:listen - listen:Executing docker restart -t=0 shippable-mexec-5730cb632461c00c002904b0
Booting up MEXEC..
INFO:listen - listen:Inside MEXEC listener
INFO:listen - listen:MEXEC boot successful
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
```

**Comment by manishas** [comment]
@ric03uec can you take a look at this?

**Comment by ric03uec** [comment]
@amondnet it seems like shippable agent is not able to connect to the queue server. The exception trace  you posted is a result of an unrelated bug which we're now fixing. Can you please check your network settings to verify that all outbound traffic from the machine is allowed. Since the agent was actually connecting yesterday and now its just failing to connect, I'm guessing it has to do something with network settings.
If this doesn't get fixed, we can get on a call to get this sorted out.

**Comment by amondnet** [comment]
@ric03uec 
All outbound traffic from the machine is allowed. 
I installed [jumpcloud](https://jumpcloud.com) agent on my build machines yesterday. I removed the agent and reinitialize node. Then the problems were solved.
 
http://support.jumpcloud.com/knowledgebase/articles/265650

> Configuration Files Modified by JumpCloud
> - /etc/ssh/sshd_config - one or more of the following parameters: [ PermitRootLogin, PasswordAuthentication, UsePAM, PubkeyAuthentication, ChallengeResponseAuthentication]
> - /etc/pam.d/sshd,/etc/pam.d/system-auth,/etc/pam.d/password-auth - JumpCloud adds the pam_google _authenticator.so plugin line to one of these files depending on your Linux distro.
> - /etc/sudoers - JumpCloud appends sudo users, and then manages the users it appends
> - /root/.ssh/authorized_keys, /home/<USER>/.ssh/authorized_keys - JumpCloud manages this based on users having uploaded public keys to JumpCloud
> - /etc/syslog.conf, /etc/rsyslog.d/jumpcloud.conf - JumpCloud appends a local host address (127.0.0.1:14028) when enabling Syslog for the Events API (logging user events).  For more information, refer to our KB for JumpClouds Events API


It's probably why the shippable agent is not able to connect to the queue server.

**Comment by manishas** [comment]
Closing this since it is resolved.
