### ISSUE TITLE
Cannot expand environment variables in new run summary

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2685]
The new run summary (which is really nice BTW) shows an expander for environment variables similar to the one within single jobs. However, clicking it does nothing where I'd expect the environment variables to be shown.

**Comment by mbrodala** [comment]
I also see the following error on page load:

```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.15/ngRepeat/dupes?p0=matrixVar%20in%20job.env&p1=string%3A%23SHIPPABLE_SECURE_VARIABLE&p2=%23SHIPPABLE_SECURE_VARIABLE
    at Error (native)
    at https://app.shippable.com/ngApp/lib.min.js:20:2802
    at https://app.shippable.com/ngApp/lib.min.js:23:22265
    at Object.fn (https://app.shippable.com/ngApp/lib.min.js:21:29477)
    at m.$digest (https://app.shippable.com/ngApp/lib.min.js:21:30093)
    at m.$apply (https://app.shippable.com/ngApp/lib.min.js:21:31523)
    at f (https://app.shippable.com/ngApp/lib.min.js:21:8662)
    at s (https://app.shippable.com/ngApp/lib.min.js:21:10805)
    at XMLHttpRequest.v.onload (https://app.shippable.com/ngApp/lib.min.js:21:11348)
```

**Comment by a-murphy** [comment]
It should be working now.  Thank you for including the error message from the console; it made it really easy to fix.

**Comment by manishas** [comment]
Closing this.

**Comment by mbrodala** [comment]
Thanks a lot for fixing. :-)
