### ISSUE TITLE
awsebcli fails

### ISSUE THREAD

**Issue by knowredev** [Shippable/support#2759]
Hi, the following build starts to fail recently on AWS EB integration:
https://app.shippable.com/runs/577291b95de4de0c00e3cb2c

```
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.7.7', 'console_scripts', 'eb')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/ebcore.py", line 43, in <module>
    from . import ebglobals, base, io, hooks
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/hooks.py", line 21, in <module>
    from ..lib import aws
  File "/usr/local/lib/python2.7/dist-packages/ebcli/lib/aws.py", line 22, in <module>
    from botocore.config import Config
ImportError: cannot import name Config
```

The `awsebcli` seems to be started to have `ImportError` on `botocore.config` and I cannot think any way to fix it in user zone. The strange thing is that I don't experience this in the other project with very similar setting.

Thanks in advance,
Kurt

**Comment by a-murphy** [comment]
Someone else has reported a similar error recently and fixed it by upgrading `botocore` (#2757).  So you may want to try upgrading `botocore` at the end of your `post_ci` section to see if that helps.

It's odd that this suddenly appeared without changing anything; we'll have to look into what may have caused it.

**Comment by a-murphy** [comment]
I think I've found the cause of the sudden failure.  A new version of `awsebcli` was released, and `pip` is installing the new version.  3.7.6 runs without an error, but it looks like 3.7.7 needs a newer version of `botocore`.

**Comment by bobbydeveaux** [comment]
The solution is here:
https://github.com/Shippable/support/issues/2757
