### ISSUE TITLE
ImportError: cannot import name Config

### ISSUE THREAD

**Issue by wegenern** [Shippable/support#2760]
With no changes to our branches, we are now getting the following error in the Script.  None of our branches can currently build due to this.

````
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.7.7', 'console_scripts', 'eb')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/ebcore.py", line 43, in <module>
    from . import ebglobals, base, io, hooks
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/hooks.py", line 21, in <module>
    from ..lib import aws
  File "/usr/local/lib/python2.7/dist-packages/ebcli/lib/aws.py", line 22, in <module>
    from botocore.config import Config
ImportError: cannot import name Config
```

**Comment by abhijitkini** [comment]
@wegenern can you give a link to your build?

**Comment by stephanielingwood** [comment]
Hi @wegenern,

We've seen this error a few times today so far - looks like a new version of awsebcli was released, and is looking for a newer version of botocore. For a fix, check out https://github.com/Shippable/support/issues/2759. 

Marking this a duplicate of the above issue.

**Comment by wegenern** [comment]
#2759 took care of it.  Thanks again!

**Comment by bobbydeveaux** [comment]
@wegenern you should have searched pre-existing issues first :)

https://github.com/Shippable/support/issues/2757 <-- solution the other day.
