### ISSUE TITLE
Deploy to AWS ElasticBeanstalk failing where previously worked

### ISSUE THREAD

**Issue by designreact** [Shippable/support#2796]
Here are two builds of the same commit one from 2016/06/23 and the other today (2016/07/11)
Where it worked: https://app.shippable.com/runs/576bd32fc6aa160c003eb8ec/
Now it fails: https://app.shippable.com/runs/57836cf0b020cd0c007d7a03/

I'm not sure whether any updates were made to shippable which I missed but it seems there is a config load failure which is preventing my builds syncing with AWS EB. Please see error below.

```
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.7.7', 'console_scripts', 'eb')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/ebcore.py", line 43, in <module>
    from . import ebglobals, base, io, hooks
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/hooks.py", line 21, in <module>
    from ..lib import aws
  File "/usr/local/lib/python2.7/dist-packages/ebcli/lib/aws.py", line 22, in <module>
    from botocore.config import Config
ImportError: cannot import name Config
```

**Comment by designreact** [comment]
It looks like the aws_eb_deploy > eb --version returns an error also. 

```
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.7.7', 'console_scripts', 'eb')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/ebcore.py", line 43, in <module>
    from . import ebglobals, base, io, hooks
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/hooks.py", line 21, in <module>
    from ..lib import aws
  File "/usr/local/lib/python2.7/dist-packages/ebcli/lib/aws.py", line 22, in <module>
    from botocore.config import Config
ImportError: cannot import name Config
```

**Comment by bobbydeveaux** [comment]
You can see a fix for this here:

https://github.com/Shippable/support/issues/2757

**Comment by designreact** [comment]
That sorted it! - Thanks @bobbydeveaux
