### ISSUE TITLE
Connection time out while trying to connect to RDS instance

### ISSUE THREAD

**Issue by kqdtran** [Shippable/support#2842]
### Description of your issue:
Hi, I'm trying to build a project on Shippable. Our backend stack is Django 1.9 running on Amazon RDS's PostgreSQL. I'm currently stuck at this step in my shippable.yml file:

`coverage run --source="." manage.py test`

, where the error is:

```
Traceback (most recent call last):
  File "manage.py", line 36, in <module>
    execute_from_command_line(sys.argv)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/test/runner.py", line 532, in run_tests
    old_config = self.setup_databases()
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/test/runner.py", line 482, in setup_databases
    self.parallel, **kwargs
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/test/runner.py", line 726, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 56, in create_test_db
    self._create_test_db(verbosity, autoclobber, keepdb)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 165, in _create_test_db
    with self._nodb_connection.cursor() as cursor:
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: Connection timed out
	Is the server running on host "xxx.rds.amazonaws.com" (xxx) and accepting TCP/IP connections on port 5432?
``` 

What can I do to get around this? Is there an IP range from Shippable/Docker that I can allow on our security group for the RDS instance?

- Link to the build failure: https://app.shippable.com/runs/579aa1c8f1213e0b00ef3055/1/console

**Comment by cratz** [comment]
Hi,
is it necessary to connect to RDS while building the project or is a local PostgreSQL (inside the build container) suitable?

**Comment by kqdtran** [comment]
This is now resolved. We decided to create a local PostgreSQL instance and run our tests on that. Thanks!
