### ISSUE TITLE
Previously working nodeJs builds now failing with gulp TypeError

### ISSUE THREAD

**Issue by hunt3ri** [Shippable/support#2890]
Hi

nodejs 4.4.3 Builds that correctly built on Friday 19th now no longer build when we rebuild them, failing with a strange TypeErrror that I can't reproduce.  Has something changed over the weekend, I'm wondering if it's a permissions problem?  We can successfully build locally.

Error from build is here:

TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob2base/index.js:9:25)
    at setToBase (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob2base/index.js:48:12)
    at module.exports (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/root/src/github.com/thinkWhere/Map-Store-App/gulpfile.js:124:10)
    at module.exports (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/root/src/github.com/thinkWhere/Map-Store-App/node_modules/gulp/node_modules/orchestrator/index.js:214:10)

**Comment by rageshkrishna** [comment]
@hunt3ri I can confirm that we have not made any changes to the system over the weekend that would cause this. My guess is that some dependent npm package may have been upgraded causing things to break in gulp.

You are probably not seeing this locally because you have some version of the package in your node_modules that satisfies the version requirement. Can you please check if you are able to reproduce this issue on a fresh clone of your repository without any local node_modules directory?

**Comment by rageshkrishna** [comment]
An issue was opened in `gulp` a little earlier today for this: https://github.com/gulpjs/gulp/issues/1768

**Comment by Phalconline** [comment]
https://github.com/MoOx/reduce-css-calc

**Comment by hunt3ri** [comment]
Thanks @rageshkrishna can confirm that the problem was indeed a dependent npm package that had introduced a bug over the weekend.  (Only in the insane JS world, can you introduce a breaking change, without changing any version numbers :-S)

All our JS builds now running again, thanks for the quick response and links to relevant problem.  Happy to close this issue :+1:
