### ISSUE TITLE
Build failure installing ember-cli

### ISSUE THREAD

**Issue by TimvdEijnden** [Shippable/support#2954]
Since thursday 8 september we're experiencing this issue.

- Link to the build failure:
https://app.shippable.com/runs/57d6718eeac0e40f00096d75/1/console

Keep getting this error:
```
  mkdir -p shippable/testresults 0s  
  npm install -g bower 6s  
  npm install -g ember-cli 49s  
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> spawn-sync@1.0.15 postinstall /root/.nvm/versions/node/v4.5.0/lib/node_modules/ember-cli/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall


module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/versions/node/v4.5.0/lib/node_modules/ember-cli/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 3.19.0-51-generic
npm ERR! argv "/root/.nvm/versions/node/v4.5.0/bin/node" "/root/.nvm/versions/node/v4.5.0/bin/npm" "install" "-g" "ember-cli"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spawn-sync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/src/github.com/xxx/xxx/npm-debug.log
```

What we've tried:
* [reset_minion] in a commit
* change node versions
* clear cache for project

**Comment by TimvdEijnden** [comment]
We've fixed it by using node_modules/ember-cli/bin/ember and not installing ember-cli -g
