### ISSUE TITLE
Pipeline V2 Error - error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by nmarshall-cst** [Shippable/support#2972]
I am running into a PEM error during my deploy step to Triton (Joyent). I have successfully deployed a container to Triton via a v2 pipeline in the past. Here is the full error:

```
/home/shippable/micro/nod/stepExec/managed/deploy/run.sh 1s  
####### DEPLOY: RUN.SH ########
npm
 WARN package.json shippable-Deploy@4.0.1 No description
npm WARN package.json shippable-Deploy@4.0.1 No repository field.
npm WARN package.json shippable-Deploy@4.0.1 No README data
npm WARN package.json shippable-Deploy@4.0.1 No license field.
----> Run Deploy
Starting Deployment for: deploy-to-dev
Preparing manifests
Applying manifest overrides for demo-manifest
Summary of loadBalancers: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Summary of cluster: -- newlyAdded: 1, -- changed: 0, -- deleted: 0
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Force deployment is: true
Instantiating CloudApiAdapter
crypto.js:279
  var ret = this._handle.sign(toBuf(key), null, passphrase);
                         ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (crypto.js:279:26)
    at CloudApiAdapter.initialize (/home/shippable/micro/nod/stepExec/managed/deploy/providers/tripub/cloudApiAdapter.js:60:38)
    at Error (native)
    at _initializeCloudApiAdapter (/home/shippable/micro/nod/stepExec/managed/deploy/providers/tripub/deploy.js:91:23)
    at /home/shippable/micro/nod/stepExec/managed/deploy/node_modules/async/dist/async.js:3575:11
    at replenish (/home/shippable/micro/nod/stepExec/managed/deploy/node_modules/async/dist/async.js:872:19)
    at /home/shippable/micro/nod/stepExec/managed/deploy/node_modules/async/dist/async.js:878:27
    at /home/shippable/micro/nod/stepExec/managed/deploy/node_modules/async/dist/async.js:840:18
    at /home/shippable/micro/nod/stepExec/managed/deploy/node_modules/async/dist/async.js:3580:15
    at /home/shippable/micro/nod/stepExec/managed/deploy/node_modules/async/dist/async.js:339:29
```

I verified that my ssh key integration for Joyent is correct. Any thoughts on this?

Thanks!
Nate

- https://app.shippable.com/subscriptions/5609c11b1895ca447418ab35/pipelines/builds/57dc0d572b5f4d0f0075c77b/consoles

**Comment by trriplejay** [comment]
I think we've got a bug here. we'll take a closer look and keep you updated.

**Comment by trriplejay** [comment]
Hello,

We've addressed this bug, however in order to get your pipeline working, you're going to have to create a new Triton Public Cloud account integration (which will generate new keys).  I recommend creating a new account integration, then updating your subscription integration to reference the new account integration you've created.  Then you can delete your old account integration.  You'll also need to add the newly generated key to Triton just like with the original integration.

Sorry for the inconvenience, but thanks for helping us identify this bug!

**Comment by nmarshall-cst** [comment]
Great! Thanks for getting this fixed!
