### ISSUE TITLE
Fail to deploy to Amazon EBS, EOFError on CodeCommit

### ISSUE THREAD

**Issue by adeelhussain** [Shippable/support#3065]
Hi,
 I am facing a problem in making build, Its works well before but not today!

In my `build_on_success` i am running `eb init`  then i got this error and build failed

```
Note: Elastic Beanstalk now supports AWS CodeCommit; a fully-managed source control service. To learn more, see Docs: https://aws.amazon.com/codecommit/
Do you wish to continue with CodeCommit? (y/n)(default is n): Traceback (most recent call last):
  File "/usr/local/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.8.3', 'console_scripts', 'eb')()
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/ebcore.py", line 150, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/abstractcontroller.py", line 57, in default
    self.do_command()
  File "/usr/local/lib/python2.7/dist-packages/ebcli/controllers/initialize.py", line 150, in do_command
    io.validate_action("Do you wish to continue with CodeCommit? (y/n)(default is n)", "y")
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/io.py", line 233, in validate_action
    result = get_input(output)
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/io.py", line 156, in get_input
    result = input(output + ': ').strip()
EOFError: EOF when reading a line
```

**Comment by trriplejay** [comment]
looks like an update to ebcli caused some problems. we'll have a fix pushed shortly. I'll update when it's available.

**Comment by trriplejay** [comment]
the fix has been deployed. could you try again and let me know if you're still having problems?

**Comment by adeelhussain** [comment]
@trriplejay still have the same error :(
```
Note: Elastic Beanstalk now supports AWS CodeCommit; a fully-managed source control service. To learn more, see Docs: https://aws.amazon.com/codecommit/
Do you wish to continue with CodeCommit? (y/n)(default is n): Traceback (most recent call last):
  File "/usr/local/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.8.3', 'console_scripts', 'eb')()
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/ebcore.py", line 150, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/abstractcontroller.py", line 57, in default
    self.do_command()
  File "/usr/local/lib/python2.7/dist-packages/ebcli/controllers/initialize.py", line 150, in do_command
    io.validate_action("Do you wish to continue with CodeCommit? (y/n)(default is n)", "y")
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/io.py", line 233, in validate_action
    result = get_input(output)
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/io.py", line 156, in get_input
    result = input(output + ': ').strip()
EOFError: EOF when reading a line
```

**Comment by adeelhussain** [comment]
Hi @trriplejay 
Sorry for the delay but actually i am not able to deploy changes in the these days, actually on these days there will be huge traffic on application, i will be able to push on Thursday but i think that will be the solution that you have mention above, i will deploy again on Thursday and i think its better to close this issue for now.

Thanks :)

**Comment by adeelhussain** [comment]
Hi @trriplejay 
Thanks for the support, it works :)
