### ISSUE TITLE
cascading deployments stopped working

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#3093]
seems like something changed in cascading deployment.

My pipeline breaks with:
```
Starting Deployment for: qa-pipeline
Preparing manifests
Applying manifest overrides for flowrack-manifest
/home/shippable/micro/nod/stepExec/managed/_common/applyManifestOverrides.js:74
    at /home/shippable/micro/nod/node_modules/async/dist/async.js:878:27
    at Function._.each._.forEach (/home/shippable/micro/nod/stepExec/managed/deploy/node_modules/underscore/underscore.js:153:9)
    at /home/shippable/micro/nod/node_modules/async/dist/async.js:3575:11
    at Function._.each._.forEach (/home/shippable/micro/nod/stepExec/managed/deploy/node_modules/underscore/underscore.js:153:9)
TypeError: Cannot read property 'name' of undefined
```

Even though i do not override settings for that manifest. I have 4 manifests deployed and override settings only for one at the moment.

https://app.shippable.com/subscriptions/578f3c82eeac370c00a23846/pipelines/builds/581718972fed730e00aae8bf/consoles

**Comment by manishas** [comment]
Looking into this....

**Comment by manishas** [comment]
we'll have a fix for this soon.

**Comment by trriplejay** [comment]
@KarolAdamiec this should be fixed now.  Are you still seeing this error?

**Comment by KarolAdamiec** [comment]
everything ok now.

Thanks!
