### ISSUE TITLE
Python nosetests failing

### ISSUE THREAD

**Issue by justin8** [Shippable/support#3176]
When running `setup.py test` all tests succeed, but when using `nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml` in order to show the output in the UI, I get errors that the package colorama cannot be found

```  coverage run ./setup.py test 1s  
running test
Searching for tv-episode-parser
Reading https://pypi.python.org/simple/tv_episode_parser/
Best match: tv-episode-parser 1.0.1
Downloading https://pypi.python.org/packages/78/30/5ed050ebf2ce92b5cb02563b8e172481b602f1ae4578de1d66835ab5cffe/tv_episode_parser-1.0.1.tar.gz#md5=0e6c16650ca2644128cae370b09b2088
Processing tv_episode_parser-1.0.1.tar.gz
Writing /tmp/easy_install-fAfDSt/tv_episode_parser-1.0.1/setup.cfg
Running tv_episode_parser-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-fAfDSt/tv_episode_parser-1.0.1/egg-dist-tmp-HyjV0D
zip_safe flag not set; analyzing archive contents...
Moving tv_episode_parser-1.0.1-py2.7.egg to /root/src/github.com/justin8/tv_report/.eggs

Installed /root/src/github.com/justin8/tv_report/.eggs/tv_episode_parser-1.0.1-py2.7.egg
Searching for tqdm
Reading https://pypi.python.org/simple/tqdm/
Best match: tqdm 4.10.0
Downloading https://pypi.python.org/packages/d6/45/85dd552912ccbbcce360fd4b7310533088a56c8bcb799c31f2d1408ac7a4/tqdm-4.10.0.zip#md5=49a72a1aeb00fe0c0693ce4ae5ba0a70
Processing tqdm-4.10.0.zip
Writing /tmp/easy_install-U8yYhB/tqdm-4.10.0/setup.cfg
Running tqdm-4.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-U8yYhB/tqdm-4.10.0/egg-dist-tmp-aRk_Sg
warning: no files found matching 'RELEASE'
zip_safe flag not set; analyzing archive contents...
Moving tqdm-4.10.0-py2.7.egg to /root/src/github.com/justin8/tv_report/.eggs

Installed /root/src/github.com/justin8/tv_report/.eggs/tqdm-4.10.0-py2.7.egg
Searching for pymediainfo
Reading https://pypi.python.org/simple/pymediainfo/
Best match: pymediainfo 2.1.5
Downloading https://pypi.python.org/packages/b5/f2/5895425a44023ec84f1dbd24d1cff245b7442ebf7d7da79cd9ef31ef8925/pymediainfo-2.1.5.tar.gz#md5=124e95c97e4a2d3bedc71214a34d31af
Processing pymediainfo-2.1.5.tar.gz
Writing /tmp/easy_install-iLnjbv/pymediainfo-2.1.5/setup.cfg
Running pymediainfo-2.1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-iLnjbv/pymediainfo-2.1.5/egg-dist-tmp-6Y790t
creating /root/src/github.com/justin8/tv_report/.eggs/pymediainfo-2.1.5-py2.7.egg
Extracting pymediainfo-2.1.5-py2.7.egg to /root/src/github.com/justin8/tv_report/.eggs

Installed /root/src/github.com/justin8/tv_report/.eggs/pymediainfo-2.1.5-py2.7.egg
Searching for colorama
Reading https://pypi.python.org/simple/colorama/
Best match: colorama 0.3.7
Downloading https://pypi.python.org/packages/f0/d0/21c6449df0ca9da74859edc40208b3a57df9aca7323118c913e58d442030/colorama-0.3.7.tar.gz#md5=349d2b02618d3d39e5c6aede36fe3c1a
Processing colorama-0.3.7.tar.gz
Writing /tmp/easy_install-gNKvCG/colorama-0.3.7/setup.cfg
Running colorama-0.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gNKvCG/colorama-0.3.7/egg-dist-tmp-w6nrtt
zip_safe flag not set; analyzing archive contents...
Moving colorama-0.3.7-py2.7.egg to /root/src/github.com/justin8/tv_report/.eggs

Installed /root/src/github.com/justin8/tv_report/.eggs/colorama-0.3.7-py2.7.egg
running egg_info
creating tv_report.egg-info
writing requirements to tv_report.egg-info/requires.txt
writing tv_report.egg-info/PKG-INFO
writing top-level names to tv_report.egg-info/top_level.txt
writing dependency_links to tv_report.egg-info/dependency_links.txt
writing entry points to tv_report.egg-info/entry_points.txt
writing manifest file 'tv_report.egg-info/SOURCES.txt'
reading manifest file 'tv_report.egg-info/SOURCES.txt'
writing manifest file 'tv_report.egg-info/SOURCES.txt'
running build_ext
test_get_videos_in_list (tests.tv_report_tests) ... ok
test_is_video (tests.tv_report_tests) ... ok
test_get_codec_other (tests.test_get_codec.test_get_codec) ... ok
test_get_codec_x264 (tests.test_get_codec.test_get_codec) ... ok
test_get_codec_x265 (tests.test_get_codec.test_get_codec) ... ok
test_get_quality_height_1080p (tests.test_get_quality.test_get_quality) ... ok
test_get_quality_height_720p (tests.test_get_quality.test_get_quality) ... ok
test_get_quality_width_1080p (tests.test_get_quality.test_get_quality) ... ok
test_get_quality_width_720p (tests.test_get_quality.test_get_quality) ... ok
test_get_quality_width_sd (tests.test_get_quality.test_get_quality) ... ok
test_get_quality_width_unknown (tests.test_get_quality.test_get_quality) ... ok

----------------------------------------------------------------------
Ran 11 tests in 0.040s

OK

  coverage xml --include 'tv_report*' -o shippable/codecoverage/coverage.xml 0s  
  nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml 0s  
EE
======================================================================
ERROR: Failure: ImportError (No module named colorama)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/venv/2.7/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/root/src/github.com/justin8/tv_report/tv_report/__init__.py", line 10, in <module>
    from colorama import Fore, Style, init
ImportError: No module named colorama

======================================================================
ERROR: Failure: ImportError (No module named colorama)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/venv/2.7/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/root/src/github.com/justin8/tv_report/tests/__init__.py", line 2, in <module>
    import tv_report
  File "/root/src/github.com/justin8/tv_report/tv_report/__init__.py", line 10, in <module>
    from colorama import Fore, Style, init
ImportError: No module named colorama

----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (errors=2)
```

**Comment by Sahloul** [comment]
This issue is bogus! Since [your code](https://github.com/justin8/tv_report/blob/master/tv_report/__init__.py#L10) have the missing requirement.
Have your launched: `pip install colorama`?

**Comment by justin8** [comment]
The line above runs all the tests via `setup.py test` and it works, including importing colorama.

but then when it runs via `nosetests` it doesn't find the module at all.

Also, if you read the output from the original post
```
Searching for colorama
Reading https://pypi.python.org/simple/colorama/
Best match: colorama 0.3.7
Downloading https://pypi.python.org/packages/f0/d0/21c6449df0ca9da74859edc40208b3a57df9aca7323118c913e58d442030/colorama-0.3.7.tar.gz#md5=349d2b02618d3d39e5c6aede36fe3c1a
Processing colorama-0.3.7.tar.gz
Writing /tmp/easy_install-gNKvCG/colorama-0.3.7/setup.cfg
Running colorama-0.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gNKvCG/colorama-0.3.7/egg-dist-tmp-w6nrtt
zip_safe flag not set; analyzing archive contents...
Moving colorama-0.3.7-py2.7.egg to /root/src/github.com/justin8/tv_report/.eggs
```

You can see colorama installed directly beforehand.

**Comment by a-murphy** [comment]
Some of the suggestions in this [StackOverflow question](http://stackoverflow.com/questions/3073259/python-nose-import-error) might help.  It certainly looks like `nosetests` might be looking in the wrong place.

**Comment by justin8** [comment]
I solved this by using `pip install --upgrade .` to install the current package and follow all dependencies without having to define them outside of setup.py.
