### ISSUE TITLE
BYON builds failing after node reset

### ISSUE THREAD

**Issue by codypperson** [Shippable/support#3356]
### Description of your issue: After resetting BYON per email from shippable, all builds fail when executing /home/shippable/cexec/dist/main/main

Have reset the node from scratch several times.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure: https://app.shippable.com/runs/589b3c8daf18530f004e480e/1/console

I have troubleshooted the issue to the point where when the container boots and runs the entrypoint script "--entrypoint=/home/shippable/cexec/build.sh", when it executes the "run_build()" function this is the error we get: 

".....
Installed git-core
Looking for ssh-agent
Found ssh-agent at /usr/bin/ssh-agent
Looking for python...
Found python at /usr/bin/python
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from execute import Execute
  File "/tmp/pip-build-iqIdfk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "execute.py", line 4, in <module>
    from shippable_adapter import ShippableAdapter
  File "/tmp/pip-build-iqIdfk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "shippable_adapter.py", line 3, in <module>
    import requests
  File "/tmp/pip-build-iqIdfk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/requests/__init__.py", line 61, in <module>
  File "/tmp/pip-build-iqIdfk/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
Failed to execute script main"

I see that this script has been updated a few times today in the repo: https://github.com/Shippable/cexec/commits/master

I checked out commit c3c6024ad63dcc5d29e896d38a2336aea29140d1 for cexec and reran my build which completed successfully.

Thanks-

**Comment by himanshu0503** [comment]
@codypperson : Sorry for the issues, we've been doing some changes to our build runner and packaging for the binaries have been broken.
We've filed an internal issue for the same and will update the packaging.

**Comment by trriplejay** [comment]
We've resolved this issue. Can you reset your node again? it should load the correct packages now.

**Comment by codypperson** [comment]
I reset my node this morning and so far builds are running ok.

**Comment by abhijitkini** [comment]
Closing as resolved. Let us know if it happens again.
