### ISSUE TITLE
Issue in login using github

### ISSUE THREAD

**Issue by vrajroham** [Shippable/support#3377]
### Description of  issue:
Taking too much time for login after authorizing app from github.
Further cannot login to app. shows following error after timeout.

```javascript
TokenError: The code passed is incorrect or expired.
   at Strategy.OAuth2Strategy.parseErrorResponse (/home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:320:12)
   at Strategy.OAuth2Strategy._createOAuthError (/home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:367:16)
   at /home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /home/shippable/www/node_modules/passport-github/lib/strategy.js:77:16
   at /home/shippable/www/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:209:7
   at passBackControl (/home/shippable/www/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:134:9)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:157:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:923:12)
```

**Comment by manishas** [comment]
@vrajroham we're looking into this... please follow latest status at status.shippable.com

**Comment by vrajroham** [comment]
@manishas Service is operational now. 
Thanks for support
