### ISSUE TITLE
pip assertion errors

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3424]
https://app.shippable.com/runs/58be0069c2fe01050096c88f/1/console

The ``pip install -r requirements-tests.txt`` call is generating a number of assertion errors, such as:

```
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-5up3l_ua/psycopg2/setup.py", line 624, in <module>
      ext_modules=ext)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
```

These appear to be ignored, but worry me regardless.

I am still trying to debug from this end, however I suspect it might be related to Python 3.5 and the build environment.

**Comment by brianmay** [comment]
I think I worked out the issue. The version of wheel is too old.

```
pip install -U wheel
```

Fixes the problem and makes it considerably faster too.
