### ISSUE TITLE
node.js builds all of a sudden failing during gulp step

### ISSUE THREAD

**Issue by gcoombe** [Shippable/support#3524]
This afternoon our builds starting failing all of a sudden on a gulp step for linting our code.  We cannot reproduce this error locally and tried rebuilding old builds which had passed and they also throw this error.  

The console shows:

  ``` gulp lint 0s  
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.10.2/lib/node_modules/gulp/node_modules/v8flags/index.js:14:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Failure can be found at: https://app.shippable.com/github/gcoombe/fetch-home/runs/440/1/console

**Comment by phated** [comment]
Just published the fix for this.  Reinstall to get the latest deps.

**Comment by ambarish2012** [comment]
Closing this issue, since it has been addressed by @phated .
