### ISSUE TITLE
selenium webdriver firefox 47

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3555]
I want to use the following
Java 1.7
selenium webdriver firefox 47
Minimum mvn 3.2

What is the recommended shippable.yml file

**Comment by aswath-veersoft** [comment]
My shippable.yml file

language: java

jdk:
   - oraclejdk7

build:
  ci:
    - mvn verify -Pfirefox -Pjunit4testset -e
    
addons:
  firefox: "46.0"

**Comment by aswath-veersoft** [comment]
I get the following errors

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.veersoft.webdriver.VsWebDriverTest4.setUp(VsWebDriverTest4.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: GDK_BACKEND does not match available displays

**Comment by aswath-veersoft** [comment]
I had the following while using the snap-ci.com.   All the tests were passing.  
What is the equivalent in shippable.yml.  I will be using firefox 47.

sudo yum remove firefox
sudo yum install libvpx
sudo rpm -Uvh http://vault.centos.org/6.6/updates/x86_64/Packages/firefox-31.6.0-2.el6.centos.x86_64.rpm
mvn verify -Pfirefox -Pjunit4testset || true
mvn appengine:devserver_stop

**Comment by ambarish2012** [comment]
@aswath-veersoft I will get back to you with a recommendation today.

**Comment by ambarish2012** [comment]
@aswath-veersoft which version of Selenium are you running your tests with?

**Comment by aswath-veersoft** [comment]
2.53.1 selenium

**Comment by ambarish2012** [comment]
@aswath-veersoft take a look at [this doc](http://docs.shippable.com/ci/services/selenium/) to setup Selenium.

The image you are using installs v3.0.1 of Selenium. To use a different version of Selenium, you will need to script the install and startup of Selenium.

You can look at [this ym filel](https://github.com/ambarish2012/basic-selenium/blob/master/shippable.yml) to see how to do it.

**Comment by ambarish2012** [comment]
Please reopen this issue if you need any further help. Also, you might need to setup XVFB as mentioned in the selenium document.

**Comment by aswath-veersoft** [comment]
I made the changes.  I also added the XVFB.  Please see my final

language: java
jdk:
   - oraclejdk7
   
addons:
  firefox: "47.0"
  
build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    #download selenium version 2.53.1
    - mkdir ~/selenium
    - pushd ~/selenium
    - sudo wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
    - pwd && ls -lR
    #start selenium server
    - java -jar ./selenium-server-standalone-2.53.1.jar &
    - popd
    - "export DISPLAY=:99.0"
    - xvfb-run --server-args="-ac" mvn verify -Pfirefox -Pjunit4testset -e

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never

I get the following firefox errors

Running com.veersoft.webdriver.JUnit4TestSet
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
anonical Ltd.","homepageURL":null},{"locales":["ru"],"name":"Ubuntu Modifications","description":"Расширения Firefox для Ubuntu","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sl"],"name":"Ubuntu Modifications","description":"Ubuntu razširitve za Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sv-SE"],"name":"Ubuntu Modifications","description":"Ubuntu-paket för Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"Убунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1493795417242	DeferredSave.extensions.json	DEBUG	Save changes
1493795417242	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1493795417242	addons.xpi-utils	DEBUG	Updating add-on states
1493795417243	addons.xpi-utils	DEBUG	Writing add-ons list
1493795417245	addons.xpi	DEBUG	Registering manifest for /tmp/firefox/browser/features/loop@mozilla.org.xpi
1493795417246	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1493795417270	addons.xpi	DEBUG	Registering manifest for /tmp/firefox/browser/features/e10srollout@mozilla.org.xpi
1493795417270	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1493795417270	addons.xpi	DEBUG	Registering manifest for /tmp/firefox/browser/features/firefox@getpocket.com.xpi
1493795417271	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1493795417273	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1493795417273	addons.manager	DEBUG	Provider finished startup: XPIProvider
1493795417274	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1493795417274	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1493795417274	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1493795417274	addons.manager	DEBUG	Starting provider: GMPProvider
1493795417285	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1493795417285	addons.manager	DEBUG	Provider finished startup: GMPProvider
1493795417285	addons.manager	DEBUG	Starting provider: PluginProvider
1493795417285	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1493795417286	addons.manager	DEBUG	Provider finished startup: PluginProvider
1493795417286	addons.manager	DEBUG	Completed startup sequence
1493795421014	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1493795421014	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1493795421015	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1493795421169	DeferredSave.extensions.json	DEBUG	Write succeeded
1493795421170	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1493795421170	DeferredSave.extensions.json	DEBUG	Starting timer
1493795421185	addons.repository	DEBUG	No addons.json found.
1493795421186	DeferredSave.addons.json	DEBUG	Save changes
1493795421188	DeferredSave.addons.json	DEBUG	Starting timer
1493795421207	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1493795421207	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1493795421207	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1493795421211	DeferredSave.extensions.json	DEBUG	Starting write
1493795421245	DeferredSave.extensions.json	DEBUG	Write succeeded
1493795421246	DeferredSave.addons.json	DEBUG	Starting write
1493795421259	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.veersoft.webdriver.VsWebDriverTest4.setUp(VsWebDriverTest4.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by aswath-veersoft** [comment]
Please don't close hurriedly.  Thanks

**Comment by rageshkrishna** [comment]
@aswath-veersoft I've usually seen this happen when there's an incompatibility between the Selenium and Firefox versions.

An [old blog post](http://seleniumsimplified.com/2016/06/use_selenium_webdriver_jar_locally/) says this:

> Note: You need to update both Firefox to 47.0.1 and Selenium WebDriver to 2.53.1

Could you try specifying "47.0.1" as your Firefox version in the YML and see how it goes?

**Comment by aswath-veersoft** [comment]
Thanks.  47,0,1 works for selenium 2.53.1

**Comment by rageshkrishna** [comment]
Thanks for the update. I'm closing this issue now as the problem has been resolved.
