### ISSUE TITLE
Shippable IP adresses/ports for build node access (BYON)

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3734]
Does Shippable use fixed IP adresses/ports to access build nodes (BYON)? I'm asking because I'd like to restrict access to our nodes as far as possible.

**Comment by rageshkrishna** [comment]
If you're manually initializing your nodes using the downloaded script, you can completely lock it down. The only time we need to make a connection to your node is when you use the automatic initialization feature, which needs to make an SSH connection. Are you using automatic initialization?

**Comment by mbrodala** [comment]
Yes, I've used the automatic init procedure.

I *guess* Shippable needs to be able to SSH into the nodes, thus port 22 would be required to be left open. If I had an IP address (range) Shippable uses to connect to our nodes, I could add them to the firewall.

Am I correct?

**Comment by rageshkrishna** [comment]
Yes, the port you use for SSH will need to be open. The port number is configurable when you create a custom node on Shippable if you would like to use non-standard ports.

I need to look up the IPs from which you can expect to see us making these connections. Let me get back to you on this in a bit.

**Comment by rageshkrishna** [comment]
Hey @mbrodala, sorry it took so long. `52.6.173.6` is the IP address. It's unlikely that this address will ever change. Please give it a shot and let me know if you run in to any issues.

**Comment by mbrodala** [comment]
@rageshkrishna thanks. I tried to set this up accordingly but when I do, builds stop at the _Provision job node_ step. I guess at this point Shippable tries to connect via SSH.

If I check the `auth.log` of our build nodes I can indeed see that the IP address you mentioned must be correct:

```
Jul 25 08:49:05 <host> sshd[4348]: Accepted publickey for shippable from 52.6.173.6 port 52186 ssh2: RSA SHA256:<stuff>
```

Also weird is that another firewall rule with our own static IP address works perfectly fine, we can access the nodes just fine via SSH.

Any ideas?

**Comment by rageshkrishna** [comment]
We do not make any SSH connections to the nodes to run builds. I suspect that the build agent on the nodes is unable to connect to us. Can you check the docker logs on the `genexec` container on your nodes? That runs a health check when it boots up and will tell you if it was unable to connect to our message queue or API.

**Comment by mbrodala** [comment]
@rageshkrishna Can you tell me straight away what outgoing connections you need? From the genexec docker logs I can see that AMQP connections to `msg.shippable.com:5671` did fail. So for starters I'll add this to the firewall. Is there anything else?

**Comment by rageshkrishna** [comment]
Oh, I thought you were only locking down _incoming_ connections. Sorry about the misunderstanding. Outgoing, we need 5671 (for msg.shippable.com) and 443 (for api.shippable.com). That should be enough for the agent.

**Comment by mbrodala** [comment]
Yeah, just saw the GET/POST calls to `api.shippable.com`. ;-)

The firewall for our VPS blocks all traffic by default, thus I need to do hole punching which includes outgoing connections. I'll give it a try.

**Comment by mbrodala** [comment]
It's still not working as expected but I don't assume this to be caused by the Shippable agent. It's more likely that the firewall rules are not properly defined yet. I'll post back once I've figured this out since this is something which should be added to the BYON doc page.

**Comment by mbrodala** [comment]
I've now also unlocked input/output for DNS (port 53) and a `curl -I https://api.shippable.com/` now works with the firewall enabled.

However, the build still stalls as soon as the firewall is enabled. Docker logs for the `genexec` container show these:

```
2017-07-27T16:05:14.064Z - verbose: Initializing ShippableAdapter
2017-07-27T16:05:14.065Z - verbose: Initializing genExec
2017-07-27T16:05:14.066Z - verbose: Checking health of genExec|_common|checkHealth
2017-07-27T16:05:14.067Z - verbose: Checking health of genExec|micro|_healthCheck|amqpMonitor
2017-07-27T16:05:14.311Z - verbose: Connected from genExec to Q amqps://<user>:<pass>@msg.shippable.com:5671/shippable
2017-07-27T16:05:14.312Z - verbose: Closed connection from genExec to Q amqps://<user>:<pass>@msg.shippable.com:5671/shippable
2017-07-27T16:05:14.312Z - verbose: genExec|micro|_healthCheck|amqpMonitor Successful health checks
2017-07-27T16:05:14.313Z - verbose: Checking health of genExec|micro|_healthCheck|checkShippableApi
2017-07-27T16:05:14.313Z - verbose: Initializing ShippableAdapter
2017-07-27T16:05:14.466Z - verbose: genExec|micro|_healthCheck|checkShippableApi Successful health checks
2017-07-27T16:05:14.467Z - verbose: genExec|_common|updateNodeStatus Starting
2017-07-27T16:05:14.467Z - verbose: Initializing ShippableAdapter
2017-07-27T16:05:14.629Z - verbose: genExec|_common|updateNodeStatus Successfully updated node status
2017-07-27T16:05:14.630Z - verbose: Validating node status of nodeId: <hash>
2017-07-27T16:05:14.630Z - verbose: Initializing ShippableAdapter
2017-07-27T16:05:14.631Z - verbose: genExec|_common|validateNode Successfully validated node status
2017-07-27T16:05:14.631Z - verbose: Skipping service call home as this is not a serviceNode
2017-07-27T16:05:14.631Z - verbose: Validating node status of nodeId: <hash>
2017-07-27T16:05:14.632Z - verbose: Initializing ShippableAdapter
2017-07-27T16:05:14.632Z - verbose: genExec|_common|postNodeStats Successfully validated node status
2017-07-27T16:05:14.633Z - verbose: genExec|_common|checkHealth Successful health checks
2017-07-27T16:05:14.633Z - verbose: genExec| getting systemSettings
2017-07-27T16:05:14.633Z - verbose: genExec| setting runMode
2017-07-28T06:33:28.032Z - error: Failed to connect genExec to Q amqps://<user>:<pass>@msg.shippable.com:5671/shippable
2017-07-28T06:33:28.035Z - error:  Error: no heartbeat or data in last 120 seconds
    at null.<anonymous> (/home/shippable/micro/nod/node_modules/amqp/lib/connection.js:401:28)
    at Timer.listOnTimeout (timers.js:92:15)
2017-07-28T06:37:37.078Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 2 seconds
2017-07-28T06:37:38.741Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 2 seconds
2017-07-28T06:37:40.276Z - error: POST call to https://api.shippable.com/clusterNodeStats returned error. Retrying in 2 seconds
2017-07-28T06:39:40.468Z - error: POST call to https://api.shippable.com/clusterNodeStats returned error. Retrying in 2 seconds
2017-07-28T06:39:46.357Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 4 seconds
2017-07-28T06:39:49.556Z - error: POST call to https://api.shippable.com/clusterNodeStats returned error. Retrying in 4 seconds
2017-07-28T06:41:38.740Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 2 seconds
2017-07-28T06:41:40.276Z - error: POST call to https://api.shippable.com/clusterNodeStats returned error. Retrying in 2 seconds
2017-07-28T06:41:57.684Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 8 seconds
2017-07-28T06:43:38.805Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 2 seconds
2017-07-28T06:43:38.806Z - error: POST call to https://api.shippable.com/clusterNodeStats returned error. Retrying in 2 seconds
2017-07-28T06:43:48.020Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 4 seconds
2017-07-28T06:43:49.557Z - error: POST call to https://api.shippable.com/clusterNodeStats returned error. Retrying in 4 seconds
2017-07-28T06:44:12.980Z - error: GET call to https://api.shippable.com/clusterNodes/<hash>/validate returned error. Retrying in 16 seconds
```

Any ideas what I'm still missing?

**Comment by mbrodala** [comment]
This is the relevant setup of `iptables`:

```
# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
VZ_INPUT   all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
VZ_FORWARD  all  --  anywhere             anywhere            
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
DOCKER-USER  all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
VZ_OUTPUT  all  --  anywhere             anywhere            

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain VZ_FORWARD (1 references)
target     prot opt source               destination         

Chain VZ_INPUT (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  ec2-52-6-173-6.compute-1.amazonaws.com  anywhere             tcp dpt:ssh
ACCEPT     tcp  --  ec2-52-87-103-102.compute-1.amazonaws.com  anywhere             tcp spt:https
ACCEPT     tcp  --  ec2-52-200-45-105.compute-1.amazonaws.com  anywhere             tcp spt:amqps
ACCEPT     udp  --  anywhere             anywhere             udp spt:domain

Chain VZ_OUTPUT (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             ec2-52-6-173-6.compute-1.amazonaws.com  tcp spt:ssh
ACCEPT     tcp  --  anywhere             ec2-52-87-103-102.compute-1.amazonaws.com  tcp dpt:https
ACCEPT     tcp  --  anywhere             ec2-52-200-45-105.compute-1.amazonaws.com  tcp dpt:amqps
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
```

**Comment by mbrodala** [comment]
I got it resolved now. As of now I assumed that `api.shippable.com` and `msg.shippable.com` have fixed IP addresses but this doesn't seem to be the case. Pinging them from my desktop and from my build nodes revealed this. Apparently Shippable uses a CDN or similar here.

In any case I've now dropped the IP addresses from my firewall rules and only left the ports and voilá, everything works.
