### ISSUE TITLE
Shippable build failing after moving from Bitbucket to Github

### ISSUE THREAD

**Issue by treylitefm** [Shippable/support#3777]
### Description of your issue:

Here's link to our last passing build ([Bitbucket](https://app.shippable.com/bitbucket/everpath/course-platform/runs/4526/1/console))
Here's a link to one of our failing builds ([Github](https://app.shippable.com/github/skilljar/course-platform/runs/6/1/console))

The code changes from build to build are minor and unrelated to the displayed error message. Error message seems to stem from a problem in the way dependencies were installed, but I can't say for sure because our requirements did not change.

```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/root/venv/2.7/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/src/github.com/skilljar/course-platform/certificate/models.py", line 17, in <module>
    from wand.image import Image
  File "/root/venv/2.7/local/lib/python2.7/site-packages/wand/image.py", line 20, in <module>
    from .api import MagickPixelPacket, libc, libmagick, library
  File "/root/venv/2.7/local/lib/python2.7/site-packages/wand/api.py", line 163, in <module>
    'Try to install:\n  ' + msg)
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  apt-get install libmagickwand-dev
```

Help would be greatly appreciated! Thank you :)

```
#shippable.yml

install:
  - shippable_retry sudo apt-get update
  - 'shippable_retry sudo apt-get install $(grep -vE "^\s*#" Aptfile  | tr "\n" " ")'
  - pip install --upgrade pip
  - pip install -r requirements.txt

# Make folders for the reports
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - coverage run --branch --source='.' manage.py test --with-xunit --xunit-file='shippable/testresults/xunittest.xml' --verbosity=3
  - coverage xml -o shippable/codecoverage/coverage.xml
```

**Comment by a-murphy** [comment]
Your Bitbucket subscription has a much older default build image than your GitHub subscription.  ImageMagick must have been installed as a dependency of something else in the older image.  Since the older image has been deprecated for quite a while, I would suggest continuing to use the latest default image with GitHub and adding the missing dependency to your `apt-get install`.

**Comment by treylitefm** [comment]
Ah okay, sounds good. Thank you!
