### ISSUE TITLE
Shippable : Selenium Grid is not supporting.

### ISSUE THREAD

**Issue by tarpanMpatel** [Shippable/support#3808]
@manishas 
We are using the Shippable CI for our Selenium Grid automation framework. Where we have to use the Selenium server Hub which connect to Nodes. So,  my questions are
1. Is it possible to setup this Hub-node for Selenium Grid connection?
2. Shippable is supporting Headless browser automation or we can open the Browser and drive it?

We had configured our maven project and Build is successfully triggered, but we are getting the error log:

org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.F...}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: '09ba5489d799', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-126-generic', java.version: '1.8.0_131'

Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at init.SeleniumInit.setUp(SeleniumInit.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Results :

Failed tests: 
  loginIndex>SeleniumInit.setUp:296 » SessionNotCreated Unable to create new rem...

Please reply us asap.

**Comment by ambarish2012** [comment]
@Tarpan1007 you can use XVFB to emulate a display.

Please look at this doc - http://docs.shippable.com/ci/selenium/.

**Comment by Tarpan1007** [comment]
@manishas  I tried as per you mentioned to see the browser. Please refer my shippable.yml file which I have written, ---------------------------Shippabl.yml----------------------------------

language: java
jdk:
- openjdk8

addons:
firefox: "23.0"

services:
- selenium

script:
- "chmod +x /root/src/github.com/Tarpan1007/test_gmail/source/chromedriver"

build:
ci:
- sudo mvn install
- "export DISPLAY=:99.0"
- xvfb-run --server-args="-ac" mvn test

------------------------------------------------------------------------------------------------
When I am running my Build, It is downloading the pom dependencies stuffs and then directly showing the Success. No Display is showing. 


And Can you please give my 2nd Question answer?
that is like How can I connect the 
java -jar selenium-server-standalone-2.53.0.jar -role hub
java -jar selenium-server-standalone-2.53.0.jar -role node in Shippable as we have to utilize the Selenium Grid services in Shippable CI ?

Please clarify my both questions answers.
thanks

**Comment by a-murphy** [comment]
We don't support using `script` and `build: ci` in the same `shippable.yml`.  The `script` tag was part of an older format.  So, your `script` and `ci` sections should be combined in order to run both.  The resulting YML should look like this:

```YML
language: java
jdk:
  - openjdk8

addons:
  firefox: "23.0"

services:
  - selenium

build:
  ci:
    - "chmod +x /root/src/github.com/Tarpan1007/test_gmail/source/chromedriver"
    - sudo mvn install
    - "export DISPLAY=:99.0"
    - xvfb-run --server-args="-ac" mvn test
```

For your second question, I don't know much about Selenium Grid, but if you need the location of the Selenium .jar file it's available in the `SHIPPABLE_SELENIUM_BINARY` environment variable.  You should be able to use that environment variable in your `ci` section.

**Comment by ambarish2012** [comment]
Please also note that -

1. We do not show the display. Your browser runs headless.
2. Which browser and browser version do you want to run? In your yml, you are using an older version (23) of firefox.
3. Do you need a very specific version of Selenium?

**Comment by Tarpan1007** [comment]
@ambarish2012  @manishas  Sure.
Please refer the link:
http://www.seleniumhq.org/docs/07_selenium_grid.jsp          for Selenium Grid.

In Short, We are creating one Selenium Server hub and also creating another Selenium node , Which will registered to this Hub. Seems like distributed concepts.

Thanks

**Comment by Tarpan1007** [comment]
Please refer the attached Screenshot from this link: https://ibb.co/kYtRpF

Recently we are getting this issue. Also reply for this issue separately. Thanks.
