### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#3931]
I'm having trouble logging in and seeing a stack trace.

https://app.shippable.com/auth/bitbucket/{redacted}/identify?oauth_verifier={redacted}&oauth_token={redacted}

Error: Invalid request token.
   at Strategy.parseErrorResponse (/home/shippable/www/node_modules/passport-bitbucket/lib/strategy.js:171:31)
   at Strategy.OAuthStrategy._createOAuthError (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth1/lib/strategy.js:393:16)
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth1/lib/strategy.js:154:43
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:465:22
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:923:12)
   at nextTickCallbackWith2Args (node.js:511:9)

**Comment by pwarnock** [comment]
I was able to log in now.
