### ISSUE TITLE
Build error in application with react

### ISSUE THREAD

**Issue by renanrboliveira** [Shippable/support#4069]
- shippable_retry npm run build

> xxxx@0.1.0 build /root/src/github.com/xxxxx/x-to-x-ui
> npm run build-css && react-scripts build

> xxxx@0.1.0 build-css /root/src/github.com/xxxx/x-to-x-ui
> node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/

fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/root/src/github.com/xxxxxxx/x-to-x-ui/node_modules/node-sass-chokidar/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Object.getInstalledBinaries (/root/src/github.com/xxxxxxx/x-to-x-ui/node_modules/node-sass-chokidar/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/root/src/github.com/xxxxxxx/x-to-x-ui/node_modules/node-sass-chokidar/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/src/github.com/xxxxxxx/x-to-x-ui/node_modules/node-sass-chokidar/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/src/github.com/xxxxxxx/x-to-x-ui/node_modules/node-sass-chokidar/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/src/github.com/xxxxxxx/x-to-x-ui/node_modules/node-sass-chokidar/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/src/github.com/xxxxxxx/x-to-x-ui/node_modules/node-sass-chokidar/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by a-murphy** [comment]
Could you include either a link to the failing build or the project ID from the bottom corner of that page?  Is it failing to install a module, or is it failing to run your tests?  Have you tried adding `npm cache clean` before your `npm install`?

**Comment by renanrboliveira** [comment]
The build log is private. It is failing in run build, after npm install. In my pc the build is ok. 

shippable.yml
```
language: node_js
env:
  global: 
    - secure: xxx
build:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/build
  ci:
    - shippable_retry npm install
    - shippable_retry npm run build # error is here
 
  on_success:
    - pip install awscli

**Comment by renanrboliveira** [comment]
I fixed my problem. My problem was with the node version.

Thank you!
