### ISSUE TITLE
Cannot access private repositories in GitHub

### ISSUE THREAD

**Issue by pavlopochapsky** [Shippable/support#4358]
I just joined a team with private repositories and when I logged in with GitHub I gave all the possible permissions to Shippable. 

However: 
1. When I go to my profile settings, *Private* is unchecked and I can't enable it on this screen. Refreshing unchecks it, sync unchecks it.
2. If I go to Subscriptions -> GitHub -> company and enable a project, then I get to a screen where I can enable private repositories, it takes me to an error screen with this URL
https://app.shippable.com/auth/github/undefined/private

and the following on screen:
```
TypeError: Cannot read property 'wwwHostname' of undefined
   at passportRedirect (/home/shippable/www/system/authProviders/github/Strategy.js:365:47)
   at Layer.handle [as handle_request] (/home/shippable/www/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/shippable/www/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/shippable/www/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/shippable/www/node_modules/express/lib/router/layer.js:95:5)
   at /home/shippable/www/node_modules/express/lib/router/index.js:277:22
   at param (/home/shippable/www/node_modules/express/lib/router/index.js:349:14)
   at param (/home/shippable/www/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/home/shippable/www/node_modules/express/lib/router/index.js:410:3)
   at next (/home/shippable/www/node_modules/express/lib/router/index.js:271:10)
```

I'm assuming that something broke on your end.

Thanks!

**Comment by trriplejay** [comment]
we're investigating, thanks.

**Comment by trriplejay** [comment]
@pavlopochapsky can you refresh your page and try this again? I believe we've resolved the issue.

**Comment by pavlopochapsky** [comment]
@trriplejay Thanks! Seems like it works now.
