### ISSUE TITLE
Remove `desiredCount` AWS ECS daemon scheduling

### ISSUE THREAD

**Issue by jorgensoares** [Shippable/support#4567]
Hello,
 we are trying to use shippable to deploy a service to aws ecs but we get this message:
```
creating service
error creating service InvalidParameterException: The daemon scheduling strategy does not support a desired count for services. Remove the desired count value and try again
{ InvalidParameterException: The daemon scheduling strategy does not support a desired count for services. Remove the desired count value and try again
    at Request.extractError (/home/shippable/micro/nod/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/shippable/micro/nod/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/shippable/micro/nod/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
  message: 'The daemon scheduling strategy does not support a desired count for services. Remove the desired count value and try again',
  code: 'InvalidParameterException',
  time: 2018-09-20T08:32:05.344Z,
  requestId: 'a7a3d1f1-bcaf-11e8-bffc-ed666de8de7a',
  statusCode: 400,
  retryable: false,
  retryDelay: 257.3238596548386 }
```

From what I could observe we cannot schedule a service in DAEMON mode with shippable because the `desiredCount` is always being sent when it should not. According to aws docs:
```
DAEMON -The daemon scheduling strategy deploys exactly one task on each container instance in your cluster. When using this strategy, do not specify a desired number of tasks or any task placement strategies.
```

- Link to the build failure
https://app.shippable.com/github/konciergeMD/jobs/ops-log-collector-deploy-test/builds/5ba372ab437fbb1100aef352/console

**Comment by trriplejay** [comment]
unfortunately we do not currently have a way to unset the desiredCount as it always defaults to 1, regardless of strategy.  I'll open a ticket to get this fixed and let you know once it's released.

**Comment by a-murphy** [comment]
Setting `schedulingStrategy: DAEMON` in the `service` section of a dockerOptions resource will now deploy services with daemon scheduling (without a `desiredCount`) to AWS ECS in managed deploy jobs.
