### ISSUE TITLE
Unable to log in via GitHub Auth

### ISSUE THREAD

**Issue by sivel** [Shippable/support#4629]
I got a 404 error trying to restart a build, afterwards the restart button was gone.

I logged out, and then attempted to log back in again using GitHub auth, and it is failing with:

```
APIError: API rate limit exceeded for user ID 39340.
    at /home/shippable/www/node_modules/passport-github/lib/strategy.js:120:21
    at passBackControl (/home/shippable/www/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by a-murphy** [comment]
This error shows that your account has been rate-limited.  This would have also caused the 404 when you tried to rerun a build.  Please wait a few minutes and try again.  The GitHub rate limits are per hour, so you should certainly be able to log in in an hour.

In the past, we have seen rate limits occur when the GitHub account was also used to make frequent API requests to GitHub unrelated to Shippable.

**Comment by sivel** [comment]
Thank you.  It was not clear from the error that it was my own GitHub API rate limit.
