### ISSUE TITLE
InvalidParameterException: Creation of service was not idempotent

### ISSUE THREAD

**Issue by ethancooke** [Shippable/support#4753]
### Description of your issue:
For 2 newly added shippable microservices I am getting an error `InvalidParameterException: Creation of service was not idempotent` I'm not sure what parameter is considered invalid.

**Here is the error:**
```
Deploying with the role name:  AWSServiceRoleForECS
creating service
Error creating service: InvalidParameterException: Creation of service was not idempotent.
{ InvalidParameterException: Creation of service was not idempotent.
    at Request.extractError (/home/shippable/micro/nod/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/shippable/micro/nod/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/shippable/micro/nod/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
  message: 'Creation of service was not idempotent.',
  code: 'InvalidParameterException',
  time: 2019-02-19T16:08:06.392Z,
  requestId: '8ad525bd-3460-11e9-9b40-b17cd0a4a698',
  statusCode: 400,
  retryable: false,
  retryDelay: 225.47652856361978 }
Successfully created folder /build/state/
```

**Link to the build failure:**
https://app.shippable.com/bitbucket/mxitechnologies/jobs/fp-forecast-deploy-perf-ecs/builds/5c6c328c867d9e0700ed9d4e/
and
https://app.shippable.com/bitbucket/mxitechnologies/jobs/fp-auditor-deploy-perf-ecs/builds/5c6c29c7867d9e0700ed9172/

**Comment by trriplejay** [comment]
It sounds like this error can occur when you're trying to "create" a service that already exists. Could you check your ECS to see if there are already existing services for these manifests?

The services it tried to create should be named:
- `fp-auditor-deploy-perf-ecs-fp-auditor-man-staging`
- `fp-forecast-deploy-perf-ecs-fp-forecast-man-staging`

**Comment by ethancooke** [comment]
That has fixed my problem. Thank you. Deleted the existing service in ECS, let it drain, and re ran shippable. Re running shippable a second time doesn't fall back into this same problem.
