### ISSUE TITLE
Error when showing ENVs in grid view

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4894]
When the option *Show ENVs in grid view* in the project settings is set up to show selected environment variables, the list of jobs does not load anymore.

There are errors shown in the browser console in this case:

```
lib.min.js:17 TypeError: a.split is not a function
    at https://app.shippable.com/app/app.min.js:13:836
    at Function.s.each.s.forEach (https://app.shippable.com/app/lib.min.js:1:27891)
    at ba (https://app.shippable.com/app/app.min.js:13:805)
    at ca (https://app.shippable.com/app/app.min.js:13:1277)
    at Function.s.map.s.collect (https://app.shippable.com/app/lib.min.js:1:28107)
    at https://app.shippable.com/app/app.min.js:12:26099
    at https://app.shippable.com/app/app.min.js:27:9657
    at https://app.shippable.com/app/lib.min.js:17:17807
    at n.$eval (https://app.shippable.com/app/lib.min.js:17:24798)
    at n.$digest (https://app.shippable.com/app/lib.min.js:17:23335) Possibly unhandled rejection: {}
lib.min.js:17 TypeError: a.split is not a function
    at https://app.shippable.com/app/app.min.js:13:836
    at Function.s.each.s.forEach (https://app.shippable.com/app/lib.min.js:1:27891)
    at ba (https://app.shippable.com/app/app.min.js:13:805)
    at aa (https://app.shippable.com/app/app.min.js:13:270)
    at https://app.shippable.com/app/app.min.js:12:25420
    at Function.s.map.s.collect (https://app.shippable.com/app/lib.min.js:1:28107)
    at https://app.shippable.com/app/app.min.js:12:25369
    at Object.getByProjectId (https://app.shippable.com/app/app.min.js:24:6619)
    at B (https://app.shippable.com/app/app.min.js:12:25287)
    at https://app.shippable.com/app/lib.min.js:17:17807 Possibly unhandled rejection: {}
app.min.js:16 grid-view: 0.6220703125ms
```

Clearing that field restores the grid.

(See project `54f05f3c5ab6cc13528f27b7` for example.)

**Comment by mbrodala** [comment]
We won't be using Shippable anymore.

But thanks so far!
