### ISSUE TITLE
Ruby 2.5.8 not building

### ISSUE THREAD

**Issue by gerardocdc** [Shippable/support#5076]
### Description of your issue:
After upgrading from ruby 2.5.7 to ruby 2.5.8 the build step fails with the following error:

 bundle package --all
/usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /root/src/bitbucket.org/5miles_nl/xl-skillbuilder/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
	from /usr/local/rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
	from /usr/local/rvm/gems/ruby-2.5.8/bin/bundle:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.5.8/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.5.8/bin/ruby_executable_hooks:24:in `<main>'

Before the Gemfile used bundler version 1.17.3 and now 2.1.4

Build failure
https://app.shippable.com/bitbucket/5miles_nl/xl-skillbuilder/runs/593/1/console

Scripts
Gemfile.lock and shippable.yml

[Archive.zip](https://github.com/Shippable/support/files/4550908/Archive.zip)

Log
5miles_nl-xl-skillbuilder-593.1.log

**Comment by a-murphy** [comment]
If you haven't specified 2.1.4, similar errors have been reported in https://github.com/rubygems/rubygems/issues for Ruby 2.7.0 with a suggested workaround to reinstall the default bundler gemspec by running `gem update --system 3.0.8 && gem update --system`.

The `setup_ruby` section of the logs shows that bundler version 1.17.3 was installed, not 2.1.4, so if you wanted 2.1.4, you'll need to add a command to your script to install it.
