### ISSUE TITLE
Unable to access shippable (API rate limit error)

### ISSUE THREAD

**Issue by buckett** [Shippable/support#5145]
### Description of your issue:
When accessing https://app.shippable.com/ I get redirected to:

https://app.shippable.com/auth/github/58a7c5789433b00f00ab373a/identify?redirectUrl=/&code=8221f029e77703d3cbde

and shown an error of:

APIError: API rate limit exceeded for user ID 5921.
    at /home/shippable/www/node_modules/passport-github/lib/strategy.js:120:21
    at passBackControl (/home/shippable/www/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

then refreshing the page I get:

TokenError: The code passed is incorrect or expired.
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:320:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:367:16)
    at /home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /home/shippable/www/node_modules/passport-github/lib/strategy.js:77:16
    at /home/shippable/www/node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (/home/shippable/www/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)

**Comment by buckett** [comment]
Clearing browser storage and attempting to login again results in the same error.

**Comment by a-murphy** [comment]
It looks like you were rate limited by GitHub.  Could you try again?

**Comment by buckett** [comment]
Ok, I've just hit this again. It's becoming a bit of a pain and is a critical problem if we are trying to make a release.
