### ISSUE TITLE
[BUG] Shippable fail when add two dedicated host

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#823]
I create a yml file with next configuration
```yaml
language: python
build_image: myorg/myimage
python:
  - "2.7"
env:
  - VERSION="8.0" INCLUDE="0"
  - VERSION="7.0" UNIT_TEST="1"
```

__First environment__
```yaml
   ...
  - VERSION="8.0" INCLUDE="0"
  ...
```
Work fine and has green color.

__Second environment__
```yaml
   ...
  - VERSION="7.0" UNIT_TEST="1"
  ...
```
Show a error in boot section.
```bash
Boot ✗
 Checking Image vauxoo/odoo-80-image-shippable-auto
 Running container
Downloading/unpacking virtualenv==1.11.4

  Cannot fetch index base URL https://pypi.python.org/simple/

  Could not find any downloads that satisfy the requirement virtualenv==1.11.4

Cleaning up...

No distributions at all found for virtualenv==1.11.4

Storing debug log for failure in /root/.pip/pip.log

--2014-11-27 05:40:17--  https://raw.github.com/pypa/pip/master/contrib/get-pip.py

Resolving raw.github.com (raw.github.com)... failed: Name or service not known.

wget: unable to resolve host address 'raw.github.com'

python: can't open file 'get-pip.py': [Errno 2] No such file or directory

Downloading/unpacking virtualenv==1.11.4

  Cannot fetch index base URL https://pypi.python.org/simple/

  Could not find any downloads that satisfy the requirement virtualenv==1.11.4

Cleaning up...

No distributions at all found for virtualenv==1.11.4

Storing debug log for failure in /root/.pip/pip.log

/home/shippable/wrk/boot.sh: line 39: virtualenv: command not found

/home/shippable/wrk/boot.sh: line 40: /root/ve/bin/activate: No such file or directory

Downloading/unpacking pika==0.9.13 (from -r requirements.txt (line 1))

  Cannot fetch index base URL https://pypi.python.org/simple/

  Could not find any downloads that satisfy the requirement pika==0.9.13 (from -r requirements.txt (line 1))

Cleaning up...

No distributions at all found for pika==0.9.13 (from -r requirements.txt (line 1))

Storing debug log for failure in /root/.pip/pip.log



Host *

	StrictHostKeyChecking no

boot successful

error occurred while booting : python: can't open file 'get-pip.py': [Errno 2] No such file or directory
: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 80, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 130, in execute_step
    raise e
Exception: error occurred while booting : python: can't open file 'get-pip.py': [Errno 2] No such file or directory
```

I try re-build and now is fine.
But sometime show same error.

**Comment by moylop260** [comment]
I'am using now only one server.
