### ISSUE TITLE
Docker Pull Fails

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#922]
Docker login
 Docker pull shippableimages/ubuntu1404_nodejs:latest
HTTP code: 502: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 98, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 164, in execute_step
    raise e
Exception: HTTP code: 502

This has all our builds failing right now...

**Comment by manishas** [comment]
Closing this issue since it has been resolved.
