### ISSUE TITLE
NodeJS and Redis

### ISSUE THREAD

**Issue by 0505gonzalez** [Shippable/support#944]
Hello,

I am trying out shippable and am trying to get my tests to pass, but I keep getting an error when the app tries to connect to redis. Here is my yml: 

```
# build image from Docker Hub (see https://registry.hub.docker.com/repos/shippableimages/)
build_image: shippableimages/ubuntu1404_nodejs

# language setting
language: node_js

# version numbers
node_js:
    - 0.10.25

# DB servers
services:
    - mongodb
    - redis

# Install dependencies required before npm install or test suite
before_install: npm install -g grunt-cli

# Install dependencies
install:
    - npm install

# Run test cases
script:
    - grunt test
```
and there error I get is: 

```
 1) get accounts "before all" hook:
     Uncaught Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
      at RedisClient.on_error (/root/workspace/src/github.com/xendit/xendit-rest/node_modules/redis/index.js:196:24)
      at Socket.<anonymous> (/root/workspace/src/github.com/xendit/xendit-rest/node_modules/redis/index.js:106:14)
      at Socket.emit (events.js:95:17)
      at net.js:440:14
      at process._tickDomainCallback (node.js:463:13)
```

**Comment by manishas** [comment]
@0505gonzalez the language specific images do not come pre-installed with services, so you'll need to install (using apt-get install) and start redis (and mongodb) in your yml. Let me know if you need help with this.

**Comment by 0505gonzalez** [comment]
That makes sense, thanks for the help.

**Comment by manishas** [comment]
Closing.

**Comment by 0505gonzalez** [comment]
How long would the redis/mongo installations take to install? They seem to be taking a really long time and I get no feedback as to whether the installation is still happening. Could you let me know what I should be expecting?

```
before_script:
    - sudo apt-get install redis-server
    - sudo apt-get install mongodb
    - sudo /usr/bin/redis-server
    - sudo /usr/bin/mongod
```

**Comment by 0505gonzalez** [comment]
The output I get is: 
```
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libjemalloc1 redis-tools
The following NEW packages will be installed:
  libjemalloc1 redis-server redis-tools
0 upgraded, 3 newly installed, 0 to remove and 19 not upgraded.
Need to get 410 kB of archives.
After this operation, 1,272 kB of additional disk space will be used.
```

**Comment by rageshkrishna** [comment]
Please try adding `-y` to your apt-get install like so:
````
before_script:
    - sudo apt-get install -y redis-server
    - sudo apt-get install -y mongodb
    - sudo /usr/bin/redis-server
    - sudo /usr/bin/mongod
````

This will prevent apt from waiting for confirmation from the user to continue with package installs and upgrades.
