### ISSUE TITLE
AWSEBCLI: Deployment to elastic beanstalk using the awsebcli v 3 always fails

### ISSUE THREAD

**Issue by smaiyaki** [Shippable/support#948]
I am not sure whether am doing something wrong because the tutorials on your page is based on ebconsole version 2.6.x. I am using the latest version 3.0.10 and there does not seem to be any valuable material out there with clear samples.. The error am always seeing is this:

```
 2015-01-08 20:08:45,623 (DEBUG) ebcli.lib.aws : Creating new Botocore Session
-- EBCLI Version: 3.0.10
-- Python Version: 2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3]
Traceback (most recent call last):
  File "/home/shippable/build_ve/python/2.7/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.0.10', 'console_scripts', 'eb')()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/core/ebcore.py", line 99, in main
    app.run()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/core/abstractcontroller.py", line 64, in default
    self.do_command()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/controllers/deploy.py", line 62, in do_command
    operations.deploy(app_name, env_name, region, version, label, message)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/core/operations.py", line 716, in deploy
    label=label, message=message)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/core/operations.py", line 984, in create_app_version
    bucket = elasticbeanstalk.get_storage_location(region)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/lib/elasticbeanstalk.py", line 597, in get_storage_location
    response = _make_api_call('create-storage-location', region=region)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/lib/elasticbeanstalk.py", line 49, in _make_api_call
    **operation_options)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/lib/aws.py", line 96, in make_api_call
    service = _get_service(service_name)
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/ebcli/lib/aws.py", line 74, in _get_service
    raise InvalidProfileError(e)
ebcli.objects.exceptions.InvalidProfileError: The config profile (eb-clii) could not be found
Build completed
```
I have tried several things including changing the profile name to various values or even explicitly passing the profile name to the deploy command..I can see from the build logs that the profile is indeed there.. Here is config.yml

> branch-defaults:
  deploy:
    environment: django-dev
global:
  application_name: django
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-clii
  sc: git

This my shippable.yml
```
 language: python

python:
  - 2.7

# Postgres binds to 127.0.0.1 by default and is started on boot. Default username is "postgres" with no password
# Create a DB as part of before script to use it

before_script:
  - psql -c 'create database xxx;' -U xxxx
  - mkdir -p ~/.elasticbeanstalk
  - echo '[profile eb-cli]' >> ~/.elasticbeanstalk/aws_credential_file
  - echo 'AWSAccessKeyId=xxxxxxxxxx' >> ~/.elasticbeanstalk/aws_credential_file
  - echo 'AWSSecretKey='$AWSSecretKey >> ~/.elasticbeanstalk/aws_credential_file
  - echo '[profile eb-clii]' >> ~/.elasticbeanstalk/aws_credential_file
  - echo 'aws_access_key_id = xxxxxxxx' >> ~/.elasticbeanstalk/aws_credential_file
  - echo 'aws_secret_access_key = xxxxxxxxxxxx' >> ~/.elasticbeanstalk/aws_credential_file
 

# exclude
branches:
  except:
    - master  

env:
  global:
    - RDS_HOSTNAME=******************* RDS_USERNAME=********** RDS_PASSWORD="**********" RDS_DB_NAME=******* RDS_PORT=5432
    - secure: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
install:
  - pip install awsebcli
  - pip install -r requirements.txt --use-mirrors


script:
  - mkdir -p .elasticbeanstalk
  - cp config.yml .elasticbeanstalk/


after_success:
  - ls -al ~/.elasticbeanstalk/
  - cat ~/.elasticbeanstalk/aws_credential_file
  - ls -al .elasticbeanstalk/
  - cat .elasticbeanstalk/config.yml
  - eb deploy --debug

notifications:
     email:
         recipients:
             - xxxxxxx
             
         on_success: change
         on_failure: always
```
As you can see, I have added 2 profiles for testing purposes and none of them work.. I have even tried to do some cat and listing on the directories to confirm.. Let me know if am missing something

**Comment by manishas** [comment]
@smaiyaki we're looking into this now and will update our sample as well. I'll get back to you when we have it working with the new ebconsole version.

**Comment by anowak** [comment]
@smaiyaki it seems that the new `eb` tool still accepts the old configuration format, although we need to specify the path to the credential file using `AwsCredentialFile=<file location>` format in the old `config` file (see: https://github.com/gxela/awsebcli/blob/master/ebcli/core/fileoperations.py#L138)

However, this functionality can be soon deprecated, so it is possibly better to update our samples to use `config.yml` configuration files, as you have done in your build configuration.

From now on, the location for storing the credentials is `~/.aws/config` and it seems it isn't possible to specify the settings using environment variables, nor customize this path (which is a pity). I've updated my fork of one of the Beanstalk samples to use this new location and configuration format, the documentation and all the official samples will be soon updated as well: https://github.com/anowak/sample-nodejs-mysql-beanstalk/blob/ebcli-v3/shippable.yml

**Comment by smaiyaki** [comment]
@manishas and @anowak Thank you very much for the quick response..I ave updated my configuration as well and this is now working as expected. Looking forward to the updated document. Regards
