### ISSUE TITLE
Exception trying to build java gradle project

### ISSUE THREAD

**Issue by asheibani** [Shippable/support#957]
Hi,

When I try to build my project with this .yml file:

```
language: java
jdk:
  - oraclejdk7
install:
  - gradle clean assemble --stacktrace
script:
  - ./gradlew build
notifications:
 email:
      recipients:
         - test@xxx.com
```

In the install phase for 'gradle clean assemble --stacktrace' I get an exception:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/tasks/compile/Compile
	at org.springframework.boot.gradle.SpringBootPlugin.useUtf8Encoding(SpringBootPlugin.groovy:59)
	at org.springframework.boot.gradle.SpringBootPlugin.this$2$useUtf8Encoding(SpringBootPlugin.groovy)
	at org.springframework.boot.gradle.SpringBootPlugin$this$2$useUtf8Encoding.callCurrent(Unknown Source)
	at org.springframework.boot.gradle.SpringBootPlugin.apply(SpringBootPlugin.groovy:55)
	at org.springframework.boot.gradle.SpringBootPlugin.apply(SpringBootPlugin.groovy)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:131)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:37)
	at org.gradle.api.Project$apply$0.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_5dknp0ib06eqv38leoebl3npev.run(/home/shippable/workspace/src/bitbucket.com/asheibani/chronos/build.gradle:15)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 31 more
Caused by: java.lang.ClassNotFoundException: org.gradle.api.tasks.compile.Compile
	... 49 more
```

Not sure what I am missing from my .yml file.

Thanks,
Amir

**Comment by manishas** [comment]
@asheibani we're looking into this now...

**Comment by asheibani** [comment]
@manishas any updates on this issue?

**Comment by ragsden** [comment]
@asheibani Sorry for not getting back sooner. Can you send me a link to the build url? Thanks.

**Comment by asheibani** [comment]
Here is one https://app.shippable.com/builds/54bc724c66407b0d00b6742c

**Comment by pniederw** [comment]
It should be `gradlew clean assemble` rather than `gradle clean assemble`, to make sure that the correct Gradle version is used. (The stack trace reveals that the build uses a version of the Spring Boot plugin that requires Gradle 1.x, but `gradle` is presumably a 2.x version.)

**Comment by asheibani** [comment]
I tried 'gradlew', './gradlew' and 'sudo ./gradlew' and none of them work:
- https://app.shippable.com/builds/54c299a07119a70d008879f7
- https://app.shippable.com/builds/54c29a367119a70d00887a05
- https://app.shippable.com/builds/54c29ab77119a70d00887a15
This is on the  'install' phase, does the app code exist at this point to even call gradlew?

**Comment by pniederw** [comment]
I'll leave it to the Shippable folks to answer that, but wrong Gradle version is definitely the cause of the problem. For the time being you could also update your build/wrapper to Gradle 2.x. Then `gradle clean assemble` won't fail anymore.

**Comment by asheibani** [comment]
Thanks @pniederw I will upgrade it as you suggest

**Comment by asheibani** [comment]
My spring-boot-gradle-plugin was an older version and I think it had a dependency to 1.x Gradle, I had to upgrade that and now it builds fine in 2.x. My builds are fine now! Thanks!
